/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class BalanceReportGrouping {

    public static final BalanceReportGrouping STATUS_BALANCES = new BalanceReportGrouping("status-balances");
    public static final BalanceReportGrouping TRANSACTION_CATEGORIES = new BalanceReportGrouping("transaction-categories");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, BalanceReportGrouping> values = createValuesMap();
    private static final Map<String, BalanceReportGroupingEnum> enums = createEnumsMap();

    private final String value;

    private BalanceReportGrouping(String value) {
        this.value = value;
    }

    /**
     * Returns a BalanceReportGrouping with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as BalanceReportGrouping
     */ 
    @JsonCreator
    public static BalanceReportGrouping of(String value) {
        synchronized (BalanceReportGrouping.class) {
            return values.computeIfAbsent(value, v -> new BalanceReportGrouping(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<BalanceReportGroupingEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        BalanceReportGrouping other = (BalanceReportGrouping) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "BalanceReportGrouping [value=" + value + "]";
    }

    // return an array just like an enum
    public static BalanceReportGrouping[] values() {
        synchronized (BalanceReportGrouping.class) {
            return values.values().toArray(new BalanceReportGrouping[] {});
        }
    }

    private static final Map<String, BalanceReportGrouping> createValuesMap() {
        Map<String, BalanceReportGrouping> map = new LinkedHashMap<>();
        map.put("status-balances", STATUS_BALANCES);
        map.put("transaction-categories", TRANSACTION_CATEGORIES);
        return map;
    }

    private static final Map<String, BalanceReportGroupingEnum> createEnumsMap() {
        Map<String, BalanceReportGroupingEnum> map = new HashMap<>();
        map.put("status-balances", BalanceReportGroupingEnum.STATUS_BALANCES);
        map.put("transaction-categories", BalanceReportGroupingEnum.TRANSACTION_CATEGORIES);
        return map;
    }
    
    
    public enum BalanceReportGroupingEnum {

        STATUS_BALANCES("status-balances"),
        TRANSACTION_CATEGORIES("transaction-categories"),;

        private final String value;

        private BalanceReportGroupingEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

