/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6d9330c1b6d6
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * DraftTransferResponseLinks
 * 
 * <p>Links to related resources.
 */
public class DraftTransferResponseLinks {
    /**
     * The URL to this draft transfer.
     */
    @JsonProperty("self")
    private Self self;

    @JsonCreator
    public DraftTransferResponseLinks(
            @JsonProperty("self") Self self) {
        Utils.checkNotNull(self, "self");
        this.self = self;
    }

    /**
     * The URL to this draft transfer.
     */
    @JsonIgnore
    public Self self() {
        return self;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The URL to this draft transfer.
     */
    public DraftTransferResponseLinks withSelf(Self self) {
        Utils.checkNotNull(self, "self");
        this.self = self;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DraftTransferResponseLinks other = (DraftTransferResponseLinks) o;
        return 
            Utils.enhancedDeepEquals(this.self, other.self);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            self);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DraftTransferResponseLinks.class,
                "self", self);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Self self;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The URL to this draft transfer.
         */
        public Builder self(Self self) {
            Utils.checkNotNull(self, "self");
            this.self = self;
            return this;
        }

        public DraftTransferResponseLinks build() {

            return new DraftTransferResponseLinks(
                self);
        }

    }
}
