/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * EntityWebhookEventWebhookEventTypes
 * 
 * <p>The list of events to enable for this webhook. You may specify `'*'` to add all events, except those
 * that require explicit selection.
 */
public class EntityWebhookEventWebhookEventTypes {

    public static final EntityWebhookEventWebhookEventTypes PAYMENT_LINK_PAID = new EntityWebhookEventWebhookEventTypes("payment-link.paid");
    public static final EntityWebhookEventWebhookEventTypes BALANCE_TRANSACTION_CREATED = new EntityWebhookEventWebhookEventTypes("balance-transaction.created");
    public static final EntityWebhookEventWebhookEventTypes SALES_INVOICE_CREATED = new EntityWebhookEventWebhookEventTypes("sales-invoice.created");
    public static final EntityWebhookEventWebhookEventTypes SALES_INVOICE_ISSUED = new EntityWebhookEventWebhookEventTypes("sales-invoice.issued");
    public static final EntityWebhookEventWebhookEventTypes SALES_INVOICE_CANCELED = new EntityWebhookEventWebhookEventTypes("sales-invoice.canceled");
    public static final EntityWebhookEventWebhookEventTypes SALES_INVOICE_PAID = new EntityWebhookEventWebhookEventTypes("sales-invoice.paid");
    public static final EntityWebhookEventWebhookEventTypes WILDCARD = new EntityWebhookEventWebhookEventTypes("*");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EntityWebhookEventWebhookEventTypes> values = createValuesMap();
    private static final Map<String, EntityWebhookEventWebhookEventTypesEnum> enums = createEnumsMap();

    private final String value;

    private EntityWebhookEventWebhookEventTypes(String value) {
        this.value = value;
    }

    /**
     * Returns a EntityWebhookEventWebhookEventTypes with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EntityWebhookEventWebhookEventTypes
     */ 
    @JsonCreator
    public static EntityWebhookEventWebhookEventTypes of(String value) {
        synchronized (EntityWebhookEventWebhookEventTypes.class) {
            return values.computeIfAbsent(value, v -> new EntityWebhookEventWebhookEventTypes(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EntityWebhookEventWebhookEventTypesEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EntityWebhookEventWebhookEventTypes other = (EntityWebhookEventWebhookEventTypes) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EntityWebhookEventWebhookEventTypes [value=" + value + "]";
    }

    // return an array just like an enum
    public static EntityWebhookEventWebhookEventTypes[] values() {
        synchronized (EntityWebhookEventWebhookEventTypes.class) {
            return values.values().toArray(new EntityWebhookEventWebhookEventTypes[] {});
        }
    }

    private static final Map<String, EntityWebhookEventWebhookEventTypes> createValuesMap() {
        Map<String, EntityWebhookEventWebhookEventTypes> map = new LinkedHashMap<>();
        map.put("payment-link.paid", PAYMENT_LINK_PAID);
        map.put("balance-transaction.created", BALANCE_TRANSACTION_CREATED);
        map.put("sales-invoice.created", SALES_INVOICE_CREATED);
        map.put("sales-invoice.issued", SALES_INVOICE_ISSUED);
        map.put("sales-invoice.canceled", SALES_INVOICE_CANCELED);
        map.put("sales-invoice.paid", SALES_INVOICE_PAID);
        map.put("*", WILDCARD);
        return map;
    }

    private static final Map<String, EntityWebhookEventWebhookEventTypesEnum> createEnumsMap() {
        Map<String, EntityWebhookEventWebhookEventTypesEnum> map = new HashMap<>();
        map.put("payment-link.paid", EntityWebhookEventWebhookEventTypesEnum.PAYMENT_LINK_PAID);
        map.put("balance-transaction.created", EntityWebhookEventWebhookEventTypesEnum.BALANCE_TRANSACTION_CREATED);
        map.put("sales-invoice.created", EntityWebhookEventWebhookEventTypesEnum.SALES_INVOICE_CREATED);
        map.put("sales-invoice.issued", EntityWebhookEventWebhookEventTypesEnum.SALES_INVOICE_ISSUED);
        map.put("sales-invoice.canceled", EntityWebhookEventWebhookEventTypesEnum.SALES_INVOICE_CANCELED);
        map.put("sales-invoice.paid", EntityWebhookEventWebhookEventTypesEnum.SALES_INVOICE_PAID);
        map.put("*", EntityWebhookEventWebhookEventTypesEnum.WILDCARD);
        return map;
    }
    
    
    public enum EntityWebhookEventWebhookEventTypesEnum {

        PAYMENT_LINK_PAID("payment-link.paid"),
        BALANCE_TRANSACTION_CREATED("balance-transaction.created"),
        SALES_INVOICE_CREATED("sales-invoice.created"),
        SALES_INVOICE_ISSUED("sales-invoice.issued"),
        SALES_INVOICE_CANCELED("sales-invoice.canceled"),
        SALES_INVOICE_PAID("sales-invoice.paid"),
        WILDCARD("*"),;

        private final String value;

        private EntityWebhookEventWebhookEventTypesEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

