/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * FeeRegion
 * 
 * <p>The applicable card fee region.
 */
public enum FeeRegion {
    AMERICAN_EXPRESS("american-express"),
    AMEX_INTRA_EEA("amex-intra-eea"),
    CARTE_BANCAIRE("carte-bancaire"),
    INTRA_EU("intra-eu"),
    INTRA_EU_CORPORATE("intra-eu-corporate"),
    DOMESTIC("domestic"),
    MAESTRO("maestro"),
    OTHER("other"),
    INTER("inter"),
    INTRA_EEA("intra_eea");

    @JsonValue
    private final String value;

    FeeRegion(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<FeeRegion> fromValue(String value) {
        for (FeeRegion o: FeeRegion.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

