/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ListEntitySettlementStatus
 * 
 * <p>The status of the settlement.
 */
public class ListEntitySettlementStatus {

    public static final ListEntitySettlementStatus OPEN = new ListEntitySettlementStatus("open");
    public static final ListEntitySettlementStatus PENDING = new ListEntitySettlementStatus("pending");
    public static final ListEntitySettlementStatus PAIDOUT = new ListEntitySettlementStatus("paidout");
    public static final ListEntitySettlementStatus FAILED = new ListEntitySettlementStatus("failed");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ListEntitySettlementStatus> values = createValuesMap();
    private static final Map<String, ListEntitySettlementStatusEnum> enums = createEnumsMap();

    private final String value;

    private ListEntitySettlementStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a ListEntitySettlementStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ListEntitySettlementStatus
     */ 
    @JsonCreator
    public static ListEntitySettlementStatus of(String value) {
        synchronized (ListEntitySettlementStatus.class) {
            return values.computeIfAbsent(value, v -> new ListEntitySettlementStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ListEntitySettlementStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ListEntitySettlementStatus other = (ListEntitySettlementStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ListEntitySettlementStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static ListEntitySettlementStatus[] values() {
        synchronized (ListEntitySettlementStatus.class) {
            return values.values().toArray(new ListEntitySettlementStatus[] {});
        }
    }

    private static final Map<String, ListEntitySettlementStatus> createValuesMap() {
        Map<String, ListEntitySettlementStatus> map = new LinkedHashMap<>();
        map.put("open", OPEN);
        map.put("pending", PENDING);
        map.put("paidout", PAIDOUT);
        map.put("failed", FAILED);
        return map;
    }

    private static final Map<String, ListEntitySettlementStatusEnum> createEnumsMap() {
        Map<String, ListEntitySettlementStatusEnum> map = new HashMap<>();
        map.put("open", ListEntitySettlementStatusEnum.OPEN);
        map.put("pending", ListEntitySettlementStatusEnum.PENDING);
        map.put("paidout", ListEntitySettlementStatusEnum.PAIDOUT);
        map.put("failed", ListEntitySettlementStatusEnum.FAILED);
        return map;
    }
    
    
    public enum ListEntitySettlementStatusEnum {

        OPEN("open"),
        PENDING("pending"),
        PAIDOUT("paidout"),
        FAILED("failed"),;

        private final String value;

        private ListEntitySettlementStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

