/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PaymentLinkSequenceType {
    ONEOFF("oneoff"),
    FIRST("first");

    @JsonValue
    private final String value;

    PaymentLinkSequenceType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PaymentLinkSequenceType> fromValue(String value) {
        for (PaymentLinkSequenceType o: PaymentLinkSequenceType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

