/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PaymentResponseCategories {
    MEAL("meal"),
    ECO("eco"),
    GIFT("gift"),
    SPORT_CULTURE("sport_culture");

    @JsonValue
    private final String value;

    PaymentResponseCategories(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PaymentResponseCategories> fromValue(String value) {
        for (PaymentResponseCategories o: PaymentResponseCategories.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

