/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * RouteGetResponseLinks
 * 
 * <p>An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */
public class RouteGetResponseLinks {
    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonProperty("self")
    private Url self;

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonProperty("documentation")
    private Url documentation;

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonProperty("payment")
    private Url payment;

    @JsonCreator
    public RouteGetResponseLinks(
            @JsonProperty("self") Url self,
            @JsonProperty("documentation") Url documentation,
            @JsonProperty("payment") Url payment) {
        Utils.checkNotNull(self, "self");
        Utils.checkNotNull(documentation, "documentation");
        Utils.checkNotNull(payment, "payment");
        this.self = self;
        this.documentation = documentation;
        this.payment = payment;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonIgnore
    public Url self() {
        return self;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonIgnore
    public Url documentation() {
        return documentation;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonIgnore
    public Url payment() {
        return payment;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public RouteGetResponseLinks withSelf(Url self) {
        Utils.checkNotNull(self, "self");
        this.self = self;
        return this;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public RouteGetResponseLinks withDocumentation(Url documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
        return this;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public RouteGetResponseLinks withPayment(Url payment) {
        Utils.checkNotNull(payment, "payment");
        this.payment = payment;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RouteGetResponseLinks other = (RouteGetResponseLinks) o;
        return 
            Utils.enhancedDeepEquals(this.self, other.self) &&
            Utils.enhancedDeepEquals(this.documentation, other.documentation) &&
            Utils.enhancedDeepEquals(this.payment, other.payment);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            self, documentation, payment);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RouteGetResponseLinks.class,
                "self", self,
                "documentation", documentation,
                "payment", payment);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Url self;

        private Url documentation;

        private Url payment;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder self(Url self) {
            Utils.checkNotNull(self, "self");
            this.self = self;
            return this;
        }


        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder documentation(Url documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = documentation;
            return this;
        }


        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder payment(Url payment) {
            Utils.checkNotNull(payment, "payment");
            this.payment = payment;
            return this;
        }

        public RouteGetResponseLinks build() {

            return new RouteGetResponseLinks(
                self, documentation, payment);
        }

    }
}
