/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * RouteCreateResponseType
 * 
 * <p>The type of destination. Currently only the destination type `organization` is supported.
 */
public enum RouteCreateResponseType {
    ORGANIZATION("organization");

    @JsonValue
    private final String value;

    RouteCreateResponseType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<RouteCreateResponseType> fromValue(String value) {
        for (RouteCreateResponseType o: RouteCreateResponseType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

