/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SalesInvoiceDiscountResponseType
 * 
 * <p>The type of discount.
 */
public enum SalesInvoiceDiscountResponseType {
    AMOUNT("amount"),
    PERCENTAGE("percentage");

    @JsonValue
    private final String value;

    SalesInvoiceDiscountResponseType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SalesInvoiceDiscountResponseType> fromValue(String value) {
        for (SalesInvoiceDiscountResponseType o: SalesInvoiceDiscountResponseType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

