/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f92d6e5a3ebc
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * SettlementRefundStatus
 * 
 * <p>The refund's status. Settlement refunds always have a status of `refunded`.
 */
public class SettlementRefundStatus {

    public static final SettlementRefundStatus REFUNDED = new SettlementRefundStatus("refunded");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, SettlementRefundStatus> values = createValuesMap();
    private static final Map<String, SettlementRefundStatusEnum> enums = createEnumsMap();

    private final String value;

    private SettlementRefundStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a SettlementRefundStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as SettlementRefundStatus
     */ 
    @JsonCreator
    public static SettlementRefundStatus of(String value) {
        synchronized (SettlementRefundStatus.class) {
            return values.computeIfAbsent(value, v -> new SettlementRefundStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<SettlementRefundStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        SettlementRefundStatus other = (SettlementRefundStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "SettlementRefundStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static SettlementRefundStatus[] values() {
        synchronized (SettlementRefundStatus.class) {
            return values.values().toArray(new SettlementRefundStatus[] {});
        }
    }

    private static final Map<String, SettlementRefundStatus> createValuesMap() {
        Map<String, SettlementRefundStatus> map = new LinkedHashMap<>();
        map.put("refunded", REFUNDED);
        return map;
    }

    private static final Map<String, SettlementRefundStatusEnum> createEnumsMap() {
        Map<String, SettlementRefundStatusEnum> map = new HashMap<>();
        map.put("refunded", SettlementRefundStatusEnum.REFUNDED);
        return map;
    }
    
    
    public enum SettlementRefundStatusEnum {

        REFUNDED("refunded"),;

        private final String value;

        private SettlementRefundStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

