/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bb0966563e26
 */
package com.mollie.mollie.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * UnmatchedCreditTransferActionResponseLinks
 * 
 * <p>Links to related resources.
 */
public class UnmatchedCreditTransferActionResponseLinks {
    /**
     * The URL to this action.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("self")
    private Optional<? extends UnmatchedCreditTransferActionResponseSelf> self;

    /**
     * The URL to the documentation of this endpoint.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documentation")
    private Optional<? extends UnmatchedCreditTransferActionResponseDocumentation> documentation;

    @JsonCreator
    public UnmatchedCreditTransferActionResponseLinks(
            @JsonProperty("self") Optional<? extends UnmatchedCreditTransferActionResponseSelf> self,
            @JsonProperty("documentation") Optional<? extends UnmatchedCreditTransferActionResponseDocumentation> documentation) {
        Utils.checkNotNull(self, "self");
        Utils.checkNotNull(documentation, "documentation");
        this.self = self;
        this.documentation = documentation;
    }
    
    public UnmatchedCreditTransferActionResponseLinks() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * The URL to this action.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UnmatchedCreditTransferActionResponseSelf> self() {
        return (Optional<UnmatchedCreditTransferActionResponseSelf>) self;
    }

    /**
     * The URL to the documentation of this endpoint.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UnmatchedCreditTransferActionResponseDocumentation> documentation() {
        return (Optional<UnmatchedCreditTransferActionResponseDocumentation>) documentation;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The URL to this action.
     */
    public UnmatchedCreditTransferActionResponseLinks withSelf(UnmatchedCreditTransferActionResponseSelf self) {
        Utils.checkNotNull(self, "self");
        this.self = Optional.ofNullable(self);
        return this;
    }


    /**
     * The URL to this action.
     */
    public UnmatchedCreditTransferActionResponseLinks withSelf(Optional<? extends UnmatchedCreditTransferActionResponseSelf> self) {
        Utils.checkNotNull(self, "self");
        this.self = self;
        return this;
    }

    /**
     * The URL to the documentation of this endpoint.
     */
    public UnmatchedCreditTransferActionResponseLinks withDocumentation(UnmatchedCreditTransferActionResponseDocumentation documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = Optional.ofNullable(documentation);
        return this;
    }


    /**
     * The URL to the documentation of this endpoint.
     */
    public UnmatchedCreditTransferActionResponseLinks withDocumentation(Optional<? extends UnmatchedCreditTransferActionResponseDocumentation> documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UnmatchedCreditTransferActionResponseLinks other = (UnmatchedCreditTransferActionResponseLinks) o;
        return 
            Utils.enhancedDeepEquals(this.self, other.self) &&
            Utils.enhancedDeepEquals(this.documentation, other.documentation);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            self, documentation);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UnmatchedCreditTransferActionResponseLinks.class,
                "self", self,
                "documentation", documentation);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends UnmatchedCreditTransferActionResponseSelf> self = Optional.empty();

        private Optional<? extends UnmatchedCreditTransferActionResponseDocumentation> documentation = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The URL to this action.
         */
        public Builder self(UnmatchedCreditTransferActionResponseSelf self) {
            Utils.checkNotNull(self, "self");
            this.self = Optional.ofNullable(self);
            return this;
        }

        /**
         * The URL to this action.
         */
        public Builder self(Optional<? extends UnmatchedCreditTransferActionResponseSelf> self) {
            Utils.checkNotNull(self, "self");
            this.self = self;
            return this;
        }


        /**
         * The URL to the documentation of this endpoint.
         */
        public Builder documentation(UnmatchedCreditTransferActionResponseDocumentation documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = Optional.ofNullable(documentation);
            return this;
        }

        /**
         * The URL to the documentation of this endpoint.
         */
        public Builder documentation(Optional<? extends UnmatchedCreditTransferActionResponseDocumentation> documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = documentation;
            return this;
        }

        public UnmatchedCreditTransferActionResponseLinks build() {

            return new UnmatchedCreditTransferActionResponseLinks(
                self, documentation);
        }

    }
}
