/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

/**
 * CancelSubscriptionApplicationFee
 * 
 * <p>With Mollie Connect you can charge fees on payments that your app is processing on behalf of other Mollie merchants.
 * 
 * <p>Setting an application fee on the subscription will ensure this fee is charged on each individual payment.
 * 
 * <p>Refer to the `applicationFee` parameter on the [Get payment endpoint](get-payment) documentation for more information.
 */
public class CancelSubscriptionApplicationFee {

    /**
     * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    private Optional<? extends CancelSubscriptionSubscriptionsAmount> amount;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private Optional<String> description;

    @JsonCreator
    public CancelSubscriptionApplicationFee(
            @JsonProperty("amount") Optional<? extends CancelSubscriptionSubscriptionsAmount> amount,
            @JsonProperty("description") Optional<String> description) {
        Utils.checkNotNull(amount, "amount");
        Utils.checkNotNull(description, "description");
        this.amount = amount;
        this.description = description;
    }
    
    public CancelSubscriptionApplicationFee() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CancelSubscriptionSubscriptionsAmount> amount() {
        return (Optional<CancelSubscriptionSubscriptionsAmount>) amount;
    }

    @JsonIgnore
    public Optional<String> description() {
        return description;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
     */
    public CancelSubscriptionApplicationFee withAmount(CancelSubscriptionSubscriptionsAmount amount) {
        Utils.checkNotNull(amount, "amount");
        this.amount = Optional.ofNullable(amount);
        return this;
    }

    /**
     * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
     */
    public CancelSubscriptionApplicationFee withAmount(Optional<? extends CancelSubscriptionSubscriptionsAmount> amount) {
        Utils.checkNotNull(amount, "amount");
        this.amount = amount;
        return this;
    }

    public CancelSubscriptionApplicationFee withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = Optional.ofNullable(description);
        return this;
    }

    public CancelSubscriptionApplicationFee withDescription(Optional<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CancelSubscriptionApplicationFee other = (CancelSubscriptionApplicationFee) o;
        return 
            Objects.deepEquals(this.amount, other.amount) &&
            Objects.deepEquals(this.description, other.description);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            amount,
            description);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CancelSubscriptionApplicationFee.class,
                "amount", amount,
                "description", description);
    }
    
    public final static class Builder {
 
        private Optional<? extends CancelSubscriptionSubscriptionsAmount> amount = Optional.empty();
 
        private Optional<String> description = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
         */
        public Builder amount(CancelSubscriptionSubscriptionsAmount amount) {
            Utils.checkNotNull(amount, "amount");
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        /**
         * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
         */
        public Builder amount(Optional<? extends CancelSubscriptionSubscriptionsAmount> amount) {
            Utils.checkNotNull(amount, "amount");
            this.amount = amount;
            return this;
        }

        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = Optional.ofNullable(description);
            return this;
        }

        public Builder description(Optional<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }
        
        public CancelSubscriptionApplicationFee build() {
            return new CancelSubscriptionApplicationFee(
                amount,
                description);
        }
    }
}
