/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateRefundMode
 * 
 * <p>Whether this entity was created in live mode or in test mode.
 */
public enum CreateRefundMode {
    LIVE("live"),
    TEST("test");

    @JsonValue
    private final String value;

    CreateRefundMode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateRefundMode> fromValue(String value) {
        for (CreateRefundMode o: CreateRefundMode.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

