/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateMandateStatus
 * 
 * <p>The status of the mandate. A status can be `pending` for mandates when the first payment is not yet finalized, or
 * when we did not received the IBAN yet from the first payment.
 */
public enum CreateMandateStatus {
    VALID("valid"),
    PENDING("pending"),
    INVALID("invalid");

    @JsonValue
    private final String value;

    CreateMandateStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateMandateStatus> fromValue(String value) {
        for (CreateMandateStatus o: CreateMandateStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

