/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateCustomerPaymentCustomersResponseType
 * 
 * <p>The type of product purchased. For example, a physical or a digital product.
 * 
 * <p>The `tip` payment line type is not available when creating a payment.
 */
public enum CreateCustomerPaymentCustomersResponseType {
    PHYSICAL("physical"),
    DIGITAL("digital"),
    SHIPPING_FEE("shipping_fee"),
    DISCOUNT("discount"),
    STORE_CREDIT("store_credit"),
    GIFT_CARD("gift_card"),
    SURCHARGE("surcharge"),
    TIP("tip");

    @JsonValue
    private final String value;

    CreateCustomerPaymentCustomersResponseType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateCustomerPaymentCustomersResponseType> fromValue(String value) {
        for (CreateCustomerPaymentCustomersResponseType o: CreateCustomerPaymentCustomersResponseType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

