/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.mollie.mollie.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mollie.mollie.utils.Response;
import com.mollie.mollie.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class CreateRefundResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * The newly created refund object. For a complete reference of the refund object, refer to the
     * [Get refund endpoint](get-refund) documentation.
     */
    private Optional<? extends Object> any;

    @JsonCreator
    public CreateRefundResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends Object> any) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(any, "any");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.any = any;
    }
    
    public CreateRefundResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * The newly created refund object. For a complete reference of the refund object, refer to the
     * [Get refund endpoint](get-refund) documentation.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Object> any() {
        return (Optional<Object>) any;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public CreateRefundResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateRefundResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateRefundResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * The newly created refund object. For a complete reference of the refund object, refer to the
     * [Get refund endpoint](get-refund) documentation.
     */
    public CreateRefundResponse withAny(Object any) {
        Utils.checkNotNull(any, "any");
        this.any = Optional.ofNullable(any);
        return this;
    }

    /**
     * The newly created refund object. For a complete reference of the refund object, refer to the
     * [Get refund endpoint](get-refund) documentation.
     */
    public CreateRefundResponse withAny(Optional<? extends Object> any) {
        Utils.checkNotNull(any, "any");
        this.any = any;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateRefundResponse other = (CreateRefundResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.any, other.any);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            any);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateRefundResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "any", any);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends Object> any = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * The newly created refund object. For a complete reference of the refund object, refer to the
         * [Get refund endpoint](get-refund) documentation.
         */
        public Builder any(Object any) {
            Utils.checkNotNull(any, "any");
            this.any = Optional.ofNullable(any);
            return this;
        }

        /**
         * The newly created refund object. For a complete reference of the refund object, refer to the
         * [Get refund endpoint](get-refund) documentation.
         */
        public Builder any(Optional<? extends Object> any) {
            Utils.checkNotNull(any, "any");
            this.any = any;
            return this;
        }
        
        public CreateRefundResponse build() {
            return new CreateRefundResponse(
                contentType,
                statusCode,
                rawResponse,
                any);
        }
    }
}

