/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mollie.mollie.models.components.EntitySalesInvoice;
import com.mollie.mollie.utils.SpeakeasyMetadata;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class CreateSalesInvoiceRequest {
    /**
     * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private Optional<String> idempotencyKey;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private Optional<? extends EntitySalesInvoice> entitySalesInvoice;

    @JsonCreator
    public CreateSalesInvoiceRequest(
            Optional<String> idempotencyKey,
            Optional<? extends EntitySalesInvoice> entitySalesInvoice) {
        Utils.checkNotNull(idempotencyKey, "idempotencyKey");
        Utils.checkNotNull(entitySalesInvoice, "entitySalesInvoice");
        this.idempotencyKey = idempotencyKey;
        this.entitySalesInvoice = entitySalesInvoice;
    }
    
    public CreateSalesInvoiceRequest() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     */
    @JsonIgnore
    public Optional<String> idempotencyKey() {
        return idempotencyKey;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EntitySalesInvoice> entitySalesInvoice() {
        return (Optional<EntitySalesInvoice>) entitySalesInvoice;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     */
    public CreateSalesInvoiceRequest withIdempotencyKey(String idempotencyKey) {
        Utils.checkNotNull(idempotencyKey, "idempotencyKey");
        this.idempotencyKey = Optional.ofNullable(idempotencyKey);
        return this;
    }


    /**
     * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     */
    public CreateSalesInvoiceRequest withIdempotencyKey(Optional<String> idempotencyKey) {
        Utils.checkNotNull(idempotencyKey, "idempotencyKey");
        this.idempotencyKey = idempotencyKey;
        return this;
    }

    public CreateSalesInvoiceRequest withEntitySalesInvoice(EntitySalesInvoice entitySalesInvoice) {
        Utils.checkNotNull(entitySalesInvoice, "entitySalesInvoice");
        this.entitySalesInvoice = Optional.ofNullable(entitySalesInvoice);
        return this;
    }


    public CreateSalesInvoiceRequest withEntitySalesInvoice(Optional<? extends EntitySalesInvoice> entitySalesInvoice) {
        Utils.checkNotNull(entitySalesInvoice, "entitySalesInvoice");
        this.entitySalesInvoice = entitySalesInvoice;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSalesInvoiceRequest other = (CreateSalesInvoiceRequest) o;
        return 
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey) &&
            Utils.enhancedDeepEquals(this.entitySalesInvoice, other.entitySalesInvoice);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            idempotencyKey, entitySalesInvoice);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSalesInvoiceRequest.class,
                "idempotencyKey", idempotencyKey,
                "entitySalesInvoice", entitySalesInvoice);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> idempotencyKey = Optional.empty();

        private Optional<? extends EntitySalesInvoice> entitySalesInvoice = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
         */
        public Builder idempotencyKey(String idempotencyKey) {
            Utils.checkNotNull(idempotencyKey, "idempotencyKey");
            this.idempotencyKey = Optional.ofNullable(idempotencyKey);
            return this;
        }

        /**
         * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
         */
        public Builder idempotencyKey(Optional<String> idempotencyKey) {
            Utils.checkNotNull(idempotencyKey, "idempotencyKey");
            this.idempotencyKey = idempotencyKey;
            return this;
        }


        public Builder entitySalesInvoice(EntitySalesInvoice entitySalesInvoice) {
            Utils.checkNotNull(entitySalesInvoice, "entitySalesInvoice");
            this.entitySalesInvoice = Optional.ofNullable(entitySalesInvoice);
            return this;
        }

        public Builder entitySalesInvoice(Optional<? extends EntitySalesInvoice> entitySalesInvoice) {
            Utils.checkNotNull(entitySalesInvoice, "entitySalesInvoice");
            this.entitySalesInvoice = entitySalesInvoice;
            return this;
        }

        public CreateSalesInvoiceRequest build() {

            return new CreateSalesInvoiceRequest(
                idempotencyKey, entitySalesInvoice);
        }

    }
}
