/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mollie.mollie.models.components.DeleteValuesSalesInvoice;
import com.mollie.mollie.utils.SpeakeasyMetadata;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class DeleteSalesInvoiceRequest {
    /**
     * Provide the ID of the item you want to perform this operation on.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice;

    @JsonCreator
    public DeleteSalesInvoiceRequest(
            String id,
            Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
        this.id = id;
        this.deleteValuesSalesInvoice = deleteValuesSalesInvoice;
    }
    
    public DeleteSalesInvoiceRequest(
            String id) {
        this(id, Optional.empty());
    }

    /**
     * Provide the ID of the item you want to perform this operation on.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<DeleteValuesSalesInvoice> deleteValuesSalesInvoice() {
        return (Optional<DeleteValuesSalesInvoice>) deleteValuesSalesInvoice;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Provide the ID of the item you want to perform this operation on.
     */
    public DeleteSalesInvoiceRequest withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public DeleteSalesInvoiceRequest withDeleteValuesSalesInvoice(DeleteValuesSalesInvoice deleteValuesSalesInvoice) {
        Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
        this.deleteValuesSalesInvoice = Optional.ofNullable(deleteValuesSalesInvoice);
        return this;
    }


    public DeleteSalesInvoiceRequest withDeleteValuesSalesInvoice(Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice) {
        Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
        this.deleteValuesSalesInvoice = deleteValuesSalesInvoice;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteSalesInvoiceRequest other = (DeleteSalesInvoiceRequest) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.deleteValuesSalesInvoice, other.deleteValuesSalesInvoice);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, deleteValuesSalesInvoice);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteSalesInvoiceRequest.class,
                "id", id,
                "deleteValuesSalesInvoice", deleteValuesSalesInvoice);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Provide the ID of the item you want to perform this operation on.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder deleteValuesSalesInvoice(DeleteValuesSalesInvoice deleteValuesSalesInvoice) {
            Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
            this.deleteValuesSalesInvoice = Optional.ofNullable(deleteValuesSalesInvoice);
            return this;
        }

        public Builder deleteValuesSalesInvoice(Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice) {
            Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
            this.deleteValuesSalesInvoice = deleteValuesSalesInvoice;
            return this;
        }

        public DeleteSalesInvoiceRequest build() {

            return new DeleteSalesInvoiceRequest(
                id, deleteValuesSalesInvoice);
        }

    }
}
