/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.mollie.mollie.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.mollie.mollie.utils.LazySingletonValue;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * EnableMethodResponseBody - The payment method object.
 */

public class EnableMethodResponseBody {

    /**
     * Indicates the response contains a payment method object. Will always contain the string `method` for this endpoint.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resource")
    private Optional<String> resource;

    /**
     * The unique identifier of the payment method. When used during [payment creation](create-payment), the payment method selection screen will be skipped.
     * 
     * Possible values: `alma` `applepay` `bacs` `bancomatpay` `bancontact` `banktransfer` `belfius` `billie` `blik` `creditcard` `directdebit` `eps` `giftcard` `ideal` `in3` `kbc` `klarna` `klarnapaylater` `klarnapaynow` `klarnasliceit` `mybank` `paypal` `paysafecard` `przelewy24` `riverty` `satispay` `trustly` `twint` `voucher`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<String> id;

    /**
     * The full name of the payment method.
     * 
     * If a `locale` parameter is provided, the name is translated to the given locale if possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private Optional<String> description;

    /**
     * The minimum payment amount required to use this payment method.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimumAmount")
    private Optional<? extends EnableMethodMinimumAmount> minimumAmount;

    /**
     * The maximum payment amount allowed when using this payment method. If there is no method-specific maximum, `null` is returned instead.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maximumAmount")
    private JsonNullable<? extends EnableMethodMaximumAmount> maximumAmount;

    /**
     * URLs of images representing the payment method.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("image")
    private Optional<? extends EnableMethodImage> image;

    /**
     * The payment method's activation status for this profile.
     * 
     * Possible values:
     * * `activated`: The payment method is activated and ready for use.
     * * `pending-boarding`: Mollie is waiting for you to finish onboarding in the Merchant Dashboard before the payment method can be activated.
     * * `pending-review`: Mollie needs to review your request for this payment method before it can be activated.
     * * `pending-external`: Activation of this payment method relies on you taking action with an external party, for example signing up with PayPal or a giftcard issuer.
     * * `rejected`: Your request for this payment method was rejected. Whenever Mollie rejects such a request, you will always be informed via email.
     * * `null`: This payment method was not requested.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private Optional<String> status;

    /**
     * **Optional include.** Array of objects describing the pricing configuration applicable for this payment method on your account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pricing")
    private Optional<? extends List<EnableMethodPricing>> pricing;

    /**
     * **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant for iDEAL, KBC/CBC, gift cards, and vouchers.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("issuers")
    private Optional<? extends List<EnableMethodIssuers>> issuers;

    /**
     * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("_links")
    private Optional<? extends EnableMethodLinks> links;

    @JsonCreator
    public EnableMethodResponseBody(
            @JsonProperty("resource") Optional<String> resource,
            @JsonProperty("id") Optional<String> id,
            @JsonProperty("description") Optional<String> description,
            @JsonProperty("minimumAmount") Optional<? extends EnableMethodMinimumAmount> minimumAmount,
            @JsonProperty("maximumAmount") JsonNullable<? extends EnableMethodMaximumAmount> maximumAmount,
            @JsonProperty("image") Optional<? extends EnableMethodImage> image,
            @JsonProperty("status") Optional<String> status,
            @JsonProperty("pricing") Optional<? extends List<EnableMethodPricing>> pricing,
            @JsonProperty("issuers") Optional<? extends List<EnableMethodIssuers>> issuers,
            @JsonProperty("_links") Optional<? extends EnableMethodLinks> links) {
        Utils.checkNotNull(resource, "resource");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(minimumAmount, "minimumAmount");
        Utils.checkNotNull(maximumAmount, "maximumAmount");
        Utils.checkNotNull(image, "image");
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(pricing, "pricing");
        Utils.checkNotNull(issuers, "issuers");
        Utils.checkNotNull(links, "links");
        this.resource = resource;
        this.id = id;
        this.description = description;
        this.minimumAmount = minimumAmount;
        this.maximumAmount = maximumAmount;
        this.image = image;
        this.status = status;
        this.pricing = pricing;
        this.issuers = issuers;
        this.links = links;
    }
    
    public EnableMethodResponseBody() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), JsonNullable.undefined(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Indicates the response contains a payment method object. Will always contain the string `method` for this endpoint.
     */
    @JsonIgnore
    public Optional<String> resource() {
        return resource;
    }

    /**
     * The unique identifier of the payment method. When used during [payment creation](create-payment), the payment method selection screen will be skipped.
     * 
     * Possible values: `alma` `applepay` `bacs` `bancomatpay` `bancontact` `banktransfer` `belfius` `billie` `blik` `creditcard` `directdebit` `eps` `giftcard` `ideal` `in3` `kbc` `klarna` `klarnapaylater` `klarnapaynow` `klarnasliceit` `mybank` `paypal` `paysafecard` `przelewy24` `riverty` `satispay` `trustly` `twint` `voucher`
     */
    @JsonIgnore
    public Optional<String> id() {
        return id;
    }

    /**
     * The full name of the payment method.
     * 
     * If a `locale` parameter is provided, the name is translated to the given locale if possible.
     */
    @JsonIgnore
    public Optional<String> description() {
        return description;
    }

    /**
     * The minimum payment amount required to use this payment method.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EnableMethodMinimumAmount> minimumAmount() {
        return (Optional<EnableMethodMinimumAmount>) minimumAmount;
    }

    /**
     * The maximum payment amount allowed when using this payment method. If there is no method-specific maximum, `null` is returned instead.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<EnableMethodMaximumAmount> maximumAmount() {
        return (JsonNullable<EnableMethodMaximumAmount>) maximumAmount;
    }

    /**
     * URLs of images representing the payment method.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EnableMethodImage> image() {
        return (Optional<EnableMethodImage>) image;
    }

    /**
     * The payment method's activation status for this profile.
     * 
     * Possible values:
     * * `activated`: The payment method is activated and ready for use.
     * * `pending-boarding`: Mollie is waiting for you to finish onboarding in the Merchant Dashboard before the payment method can be activated.
     * * `pending-review`: Mollie needs to review your request for this payment method before it can be activated.
     * * `pending-external`: Activation of this payment method relies on you taking action with an external party, for example signing up with PayPal or a giftcard issuer.
     * * `rejected`: Your request for this payment method was rejected. Whenever Mollie rejects such a request, you will always be informed via email.
     * * `null`: This payment method was not requested.
     */
    @JsonIgnore
    public Optional<String> status() {
        return status;
    }

    /**
     * **Optional include.** Array of objects describing the pricing configuration applicable for this payment method on your account.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<EnableMethodPricing>> pricing() {
        return (Optional<List<EnableMethodPricing>>) pricing;
    }

    /**
     * **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant for iDEAL, KBC/CBC, gift cards, and vouchers.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<EnableMethodIssuers>> issuers() {
        return (Optional<List<EnableMethodIssuers>>) issuers;
    }

    /**
     * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EnableMethodLinks> links() {
        return (Optional<EnableMethodLinks>) links;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Indicates the response contains a payment method object. Will always contain the string `method` for this endpoint.
     */
    public EnableMethodResponseBody withResource(String resource) {
        Utils.checkNotNull(resource, "resource");
        this.resource = Optional.ofNullable(resource);
        return this;
    }

    /**
     * Indicates the response contains a payment method object. Will always contain the string `method` for this endpoint.
     */
    public EnableMethodResponseBody withResource(Optional<String> resource) {
        Utils.checkNotNull(resource, "resource");
        this.resource = resource;
        return this;
    }

    /**
     * The unique identifier of the payment method. When used during [payment creation](create-payment), the payment method selection screen will be skipped.
     * 
     * Possible values: `alma` `applepay` `bacs` `bancomatpay` `bancontact` `banktransfer` `belfius` `billie` `blik` `creditcard` `directdebit` `eps` `giftcard` `ideal` `in3` `kbc` `klarna` `klarnapaylater` `klarnapaynow` `klarnasliceit` `mybank` `paypal` `paysafecard` `przelewy24` `riverty` `satispay` `trustly` `twint` `voucher`
     */
    public EnableMethodResponseBody withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    /**
     * The unique identifier of the payment method. When used during [payment creation](create-payment), the payment method selection screen will be skipped.
     * 
     * Possible values: `alma` `applepay` `bacs` `bancomatpay` `bancontact` `banktransfer` `belfius` `billie` `blik` `creditcard` `directdebit` `eps` `giftcard` `ideal` `in3` `kbc` `klarna` `klarnapaylater` `klarnapaynow` `klarnasliceit` `mybank` `paypal` `paysafecard` `przelewy24` `riverty` `satispay` `trustly` `twint` `voucher`
     */
    public EnableMethodResponseBody withId(Optional<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * The full name of the payment method.
     * 
     * If a `locale` parameter is provided, the name is translated to the given locale if possible.
     */
    public EnableMethodResponseBody withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = Optional.ofNullable(description);
        return this;
    }

    /**
     * The full name of the payment method.
     * 
     * If a `locale` parameter is provided, the name is translated to the given locale if possible.
     */
    public EnableMethodResponseBody withDescription(Optional<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * The minimum payment amount required to use this payment method.
     */
    public EnableMethodResponseBody withMinimumAmount(EnableMethodMinimumAmount minimumAmount) {
        Utils.checkNotNull(minimumAmount, "minimumAmount");
        this.minimumAmount = Optional.ofNullable(minimumAmount);
        return this;
    }

    /**
     * The minimum payment amount required to use this payment method.
     */
    public EnableMethodResponseBody withMinimumAmount(Optional<? extends EnableMethodMinimumAmount> minimumAmount) {
        Utils.checkNotNull(minimumAmount, "minimumAmount");
        this.minimumAmount = minimumAmount;
        return this;
    }

    /**
     * The maximum payment amount allowed when using this payment method. If there is no method-specific maximum, `null` is returned instead.
     */
    public EnableMethodResponseBody withMaximumAmount(EnableMethodMaximumAmount maximumAmount) {
        Utils.checkNotNull(maximumAmount, "maximumAmount");
        this.maximumAmount = JsonNullable.of(maximumAmount);
        return this;
    }

    /**
     * The maximum payment amount allowed when using this payment method. If there is no method-specific maximum, `null` is returned instead.
     */
    public EnableMethodResponseBody withMaximumAmount(JsonNullable<? extends EnableMethodMaximumAmount> maximumAmount) {
        Utils.checkNotNull(maximumAmount, "maximumAmount");
        this.maximumAmount = maximumAmount;
        return this;
    }

    /**
     * URLs of images representing the payment method.
     */
    public EnableMethodResponseBody withImage(EnableMethodImage image) {
        Utils.checkNotNull(image, "image");
        this.image = Optional.ofNullable(image);
        return this;
    }

    /**
     * URLs of images representing the payment method.
     */
    public EnableMethodResponseBody withImage(Optional<? extends EnableMethodImage> image) {
        Utils.checkNotNull(image, "image");
        this.image = image;
        return this;
    }

    /**
     * The payment method's activation status for this profile.
     * 
     * Possible values:
     * * `activated`: The payment method is activated and ready for use.
     * * `pending-boarding`: Mollie is waiting for you to finish onboarding in the Merchant Dashboard before the payment method can be activated.
     * * `pending-review`: Mollie needs to review your request for this payment method before it can be activated.
     * * `pending-external`: Activation of this payment method relies on you taking action with an external party, for example signing up with PayPal or a giftcard issuer.
     * * `rejected`: Your request for this payment method was rejected. Whenever Mollie rejects such a request, you will always be informed via email.
     * * `null`: This payment method was not requested.
     */
    public EnableMethodResponseBody withStatus(String status) {
        Utils.checkNotNull(status, "status");
        this.status = Optional.ofNullable(status);
        return this;
    }

    /**
     * The payment method's activation status for this profile.
     * 
     * Possible values:
     * * `activated`: The payment method is activated and ready for use.
     * * `pending-boarding`: Mollie is waiting for you to finish onboarding in the Merchant Dashboard before the payment method can be activated.
     * * `pending-review`: Mollie needs to review your request for this payment method before it can be activated.
     * * `pending-external`: Activation of this payment method relies on you taking action with an external party, for example signing up with PayPal or a giftcard issuer.
     * * `rejected`: Your request for this payment method was rejected. Whenever Mollie rejects such a request, you will always be informed via email.
     * * `null`: This payment method was not requested.
     */
    public EnableMethodResponseBody withStatus(Optional<String> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    /**
     * **Optional include.** Array of objects describing the pricing configuration applicable for this payment method on your account.
     */
    public EnableMethodResponseBody withPricing(List<EnableMethodPricing> pricing) {
        Utils.checkNotNull(pricing, "pricing");
        this.pricing = Optional.ofNullable(pricing);
        return this;
    }

    /**
     * **Optional include.** Array of objects describing the pricing configuration applicable for this payment method on your account.
     */
    public EnableMethodResponseBody withPricing(Optional<? extends List<EnableMethodPricing>> pricing) {
        Utils.checkNotNull(pricing, "pricing");
        this.pricing = pricing;
        return this;
    }

    /**
     * **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant for iDEAL, KBC/CBC, gift cards, and vouchers.
     */
    public EnableMethodResponseBody withIssuers(List<EnableMethodIssuers> issuers) {
        Utils.checkNotNull(issuers, "issuers");
        this.issuers = Optional.ofNullable(issuers);
        return this;
    }

    /**
     * **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant for iDEAL, KBC/CBC, gift cards, and vouchers.
     */
    public EnableMethodResponseBody withIssuers(Optional<? extends List<EnableMethodIssuers>> issuers) {
        Utils.checkNotNull(issuers, "issuers");
        this.issuers = issuers;
        return this;
    }

    /**
     * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
     */
    public EnableMethodResponseBody withLinks(EnableMethodLinks links) {
        Utils.checkNotNull(links, "links");
        this.links = Optional.ofNullable(links);
        return this;
    }

    /**
     * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
     */
    public EnableMethodResponseBody withLinks(Optional<? extends EnableMethodLinks> links) {
        Utils.checkNotNull(links, "links");
        this.links = links;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EnableMethodResponseBody other = (EnableMethodResponseBody) o;
        return 
            Objects.deepEquals(this.resource, other.resource) &&
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.description, other.description) &&
            Objects.deepEquals(this.minimumAmount, other.minimumAmount) &&
            Objects.deepEquals(this.maximumAmount, other.maximumAmount) &&
            Objects.deepEquals(this.image, other.image) &&
            Objects.deepEquals(this.status, other.status) &&
            Objects.deepEquals(this.pricing, other.pricing) &&
            Objects.deepEquals(this.issuers, other.issuers) &&
            Objects.deepEquals(this.links, other.links);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            resource,
            id,
            description,
            minimumAmount,
            maximumAmount,
            image,
            status,
            pricing,
            issuers,
            links);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EnableMethodResponseBody.class,
                "resource", resource,
                "id", id,
                "description", description,
                "minimumAmount", minimumAmount,
                "maximumAmount", maximumAmount,
                "image", image,
                "status", status,
                "pricing", pricing,
                "issuers", issuers,
                "links", links);
    }
    
    public final static class Builder {
 
        private Optional<String> resource;
 
        private Optional<String> id = Optional.empty();
 
        private Optional<String> description = Optional.empty();
 
        private Optional<? extends EnableMethodMinimumAmount> minimumAmount = Optional.empty();
 
        private JsonNullable<? extends EnableMethodMaximumAmount> maximumAmount = JsonNullable.undefined();
 
        private Optional<? extends EnableMethodImage> image = Optional.empty();
 
        private Optional<String> status = Optional.empty();
 
        private Optional<? extends List<EnableMethodPricing>> pricing = Optional.empty();
 
        private Optional<? extends List<EnableMethodIssuers>> issuers = Optional.empty();
 
        private Optional<? extends EnableMethodLinks> links = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Indicates the response contains a payment method object. Will always contain the string `method` for this endpoint.
         */
        public Builder resource(String resource) {
            Utils.checkNotNull(resource, "resource");
            this.resource = Optional.ofNullable(resource);
            return this;
        }

        /**
         * Indicates the response contains a payment method object. Will always contain the string `method` for this endpoint.
         */
        public Builder resource(Optional<String> resource) {
            Utils.checkNotNull(resource, "resource");
            this.resource = resource;
            return this;
        }

        /**
         * The unique identifier of the payment method. When used during [payment creation](create-payment), the payment method selection screen will be skipped.
         * 
         * Possible values: `alma` `applepay` `bacs` `bancomatpay` `bancontact` `banktransfer` `belfius` `billie` `blik` `creditcard` `directdebit` `eps` `giftcard` `ideal` `in3` `kbc` `klarna` `klarnapaylater` `klarnapaynow` `klarnasliceit` `mybank` `paypal` `paysafecard` `przelewy24` `riverty` `satispay` `trustly` `twint` `voucher`
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * The unique identifier of the payment method. When used during [payment creation](create-payment), the payment method selection screen will be skipped.
         * 
         * Possible values: `alma` `applepay` `bacs` `bancomatpay` `bancontact` `banktransfer` `belfius` `billie` `blik` `creditcard` `directdebit` `eps` `giftcard` `ideal` `in3` `kbc` `klarna` `klarnapaylater` `klarnapaynow` `klarnasliceit` `mybank` `paypal` `paysafecard` `przelewy24` `riverty` `satispay` `trustly` `twint` `voucher`
         */
        public Builder id(Optional<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * The full name of the payment method.
         * 
         * If a `locale` parameter is provided, the name is translated to the given locale if possible.
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * The full name of the payment method.
         * 
         * If a `locale` parameter is provided, the name is translated to the given locale if possible.
         */
        public Builder description(Optional<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        /**
         * The minimum payment amount required to use this payment method.
         */
        public Builder minimumAmount(EnableMethodMinimumAmount minimumAmount) {
            Utils.checkNotNull(minimumAmount, "minimumAmount");
            this.minimumAmount = Optional.ofNullable(minimumAmount);
            return this;
        }

        /**
         * The minimum payment amount required to use this payment method.
         */
        public Builder minimumAmount(Optional<? extends EnableMethodMinimumAmount> minimumAmount) {
            Utils.checkNotNull(minimumAmount, "minimumAmount");
            this.minimumAmount = minimumAmount;
            return this;
        }

        /**
         * The maximum payment amount allowed when using this payment method. If there is no method-specific maximum, `null` is returned instead.
         */
        public Builder maximumAmount(EnableMethodMaximumAmount maximumAmount) {
            Utils.checkNotNull(maximumAmount, "maximumAmount");
            this.maximumAmount = JsonNullable.of(maximumAmount);
            return this;
        }

        /**
         * The maximum payment amount allowed when using this payment method. If there is no method-specific maximum, `null` is returned instead.
         */
        public Builder maximumAmount(JsonNullable<? extends EnableMethodMaximumAmount> maximumAmount) {
            Utils.checkNotNull(maximumAmount, "maximumAmount");
            this.maximumAmount = maximumAmount;
            return this;
        }

        /**
         * URLs of images representing the payment method.
         */
        public Builder image(EnableMethodImage image) {
            Utils.checkNotNull(image, "image");
            this.image = Optional.ofNullable(image);
            return this;
        }

        /**
         * URLs of images representing the payment method.
         */
        public Builder image(Optional<? extends EnableMethodImage> image) {
            Utils.checkNotNull(image, "image");
            this.image = image;
            return this;
        }

        /**
         * The payment method's activation status for this profile.
         * 
         * Possible values:
         * * `activated`: The payment method is activated and ready for use.
         * * `pending-boarding`: Mollie is waiting for you to finish onboarding in the Merchant Dashboard before the payment method can be activated.
         * * `pending-review`: Mollie needs to review your request for this payment method before it can be activated.
         * * `pending-external`: Activation of this payment method relies on you taking action with an external party, for example signing up with PayPal or a giftcard issuer.
         * * `rejected`: Your request for this payment method was rejected. Whenever Mollie rejects such a request, you will always be informed via email.
         * * `null`: This payment method was not requested.
         */
        public Builder status(String status) {
            Utils.checkNotNull(status, "status");
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * The payment method's activation status for this profile.
         * 
         * Possible values:
         * * `activated`: The payment method is activated and ready for use.
         * * `pending-boarding`: Mollie is waiting for you to finish onboarding in the Merchant Dashboard before the payment method can be activated.
         * * `pending-review`: Mollie needs to review your request for this payment method before it can be activated.
         * * `pending-external`: Activation of this payment method relies on you taking action with an external party, for example signing up with PayPal or a giftcard issuer.
         * * `rejected`: Your request for this payment method was rejected. Whenever Mollie rejects such a request, you will always be informed via email.
         * * `null`: This payment method was not requested.
         */
        public Builder status(Optional<String> status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }

        /**
         * **Optional include.** Array of objects describing the pricing configuration applicable for this payment method on your account.
         */
        public Builder pricing(List<EnableMethodPricing> pricing) {
            Utils.checkNotNull(pricing, "pricing");
            this.pricing = Optional.ofNullable(pricing);
            return this;
        }

        /**
         * **Optional include.** Array of objects describing the pricing configuration applicable for this payment method on your account.
         */
        public Builder pricing(Optional<? extends List<EnableMethodPricing>> pricing) {
            Utils.checkNotNull(pricing, "pricing");
            this.pricing = pricing;
            return this;
        }

        /**
         * **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant for iDEAL, KBC/CBC, gift cards, and vouchers.
         */
        public Builder issuers(List<EnableMethodIssuers> issuers) {
            Utils.checkNotNull(issuers, "issuers");
            this.issuers = Optional.ofNullable(issuers);
            return this;
        }

        /**
         * **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant for iDEAL, KBC/CBC, gift cards, and vouchers.
         */
        public Builder issuers(Optional<? extends List<EnableMethodIssuers>> issuers) {
            Utils.checkNotNull(issuers, "issuers");
            this.issuers = issuers;
            return this;
        }

        /**
         * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
         */
        public Builder links(EnableMethodLinks links) {
            Utils.checkNotNull(links, "links");
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
         */
        public Builder links(Optional<? extends EnableMethodLinks> links) {
            Utils.checkNotNull(links, "links");
            this.links = links;
            return this;
        }
        
        public EnableMethodResponseBody build() {
            if (resource == null) {
                resource = _SINGLETON_VALUE_Resource.value();
            }            return new EnableMethodResponseBody(
                resource,
                id,
                description,
                minimumAmount,
                maximumAmount,
                image,
                status,
                pricing,
                issuers,
                links);
        }

        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_Resource =
                new LazySingletonValue<>(
                        "resource",
                        "\"method\"",
                        new TypeReference<Optional<String>>() {});
    }
}

