/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2f501b944185
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mollie.mollie.models.components.Giftcard;
import com.mollie.mollie.models.components.Voucher;
import com.mollie.mollie.utils.OneOfDeserializer;
import com.mollie.mollie.utils.TypedObject;
import com.mollie.mollie.utils.Utils.JsonShape;
import com.mollie.mollie.utils.Utils.TypeReferenceWithShape;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * EnableMethodIssuerResponseBody
 * 
 * <p>The payment method issuer object.
 */
@JsonDeserialize(using = EnableMethodIssuerResponseBody._Deserializer.class)
public class EnableMethodIssuerResponseBody {

    @JsonValue
    private final TypedObject value;
    
    private EnableMethodIssuerResponseBody(TypedObject value) {
        this.value = value;
    }

    public static EnableMethodIssuerResponseBody of(Giftcard value) {
        Utils.checkNotNull(value, "value");
        return new EnableMethodIssuerResponseBody(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static EnableMethodIssuerResponseBody of(Voucher value) {
        Utils.checkNotNull(value, "value");
        return new EnableMethodIssuerResponseBody(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.mollie.mollie.models.components.Giftcard}</li>
     * <li>{@code com.mollie.mollie.models.components.Voucher}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EnableMethodIssuerResponseBody other = (EnableMethodIssuerResponseBody) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<EnableMethodIssuerResponseBody> {

        public _Deserializer() {
            super(EnableMethodIssuerResponseBody.class, false,
                  TypeReferenceWithShape.of(new TypeReference<Giftcard>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Voucher>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(EnableMethodIssuerResponseBody.class,
                "value", value);
    }

}

