/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals {
    /**
     * Number of transactions of this type
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("count")
    private Optional<Long> count;

    /**
     * Payment type of the transactions
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("method")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod> method;

    /**
     * In case of payments transactions with card, the card issuer will be available
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cardIssuer")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer> cardIssuer;

    /**
     * In case of payments trnsactions with card, the card audience will be available.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cardAudience")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience> cardAudience;

    /**
     * In case of payments transactions with card, the card region will be available.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cardRegion")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion> cardRegion;

    /**
     * Present when the transaction represents a fee.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("feeType")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType> feeType;

    /**
     * Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prepaymentPartType")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType> prepaymentPartType;

    /**
     * Represents the transaction type
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transactionType")
    private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType> transactionType;

    @JsonCreator
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals(
            @JsonProperty("count") Optional<Long> count,
            @JsonProperty("method") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod> method,
            @JsonProperty("cardIssuer") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer> cardIssuer,
            @JsonProperty("cardAudience") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience> cardAudience,
            @JsonProperty("cardRegion") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion> cardRegion,
            @JsonProperty("feeType") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType> feeType,
            @JsonProperty("prepaymentPartType") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType> prepaymentPartType,
            @JsonProperty("transactionType") JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType> transactionType) {
        Utils.checkNotNull(count, "count");
        Utils.checkNotNull(method, "method");
        Utils.checkNotNull(cardIssuer, "cardIssuer");
        Utils.checkNotNull(cardAudience, "cardAudience");
        Utils.checkNotNull(cardRegion, "cardRegion");
        Utils.checkNotNull(feeType, "feeType");
        Utils.checkNotNull(prepaymentPartType, "prepaymentPartType");
        Utils.checkNotNull(transactionType, "transactionType");
        this.count = count;
        this.method = method;
        this.cardIssuer = cardIssuer;
        this.cardAudience = cardAudience;
        this.cardRegion = cardRegion;
        this.feeType = feeType;
        this.prepaymentPartType = prepaymentPartType;
        this.transactionType = transactionType;
    }
    
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals() {
        this(Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * Number of transactions of this type
     */
    @JsonIgnore
    public Optional<Long> count() {
        return count;
    }

    /**
     * Payment type of the transactions
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod> method() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod>) method;
    }

    /**
     * In case of payments transactions with card, the card issuer will be available
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer> cardIssuer() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer>) cardIssuer;
    }

    /**
     * In case of payments trnsactions with card, the card audience will be available.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience> cardAudience() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience>) cardAudience;
    }

    /**
     * In case of payments transactions with card, the card region will be available.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion> cardRegion() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion>) cardRegion;
    }

    /**
     * Present when the transaction represents a fee.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType> feeType() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType>) feeType;
    }

    /**
     * Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType> prepaymentPartType() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType>) prepaymentPartType;
    }

    /**
     * Represents the transaction type
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType> transactionType() {
        return (JsonNullable<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType>) transactionType;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Number of transactions of this type
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCount(long count) {
        Utils.checkNotNull(count, "count");
        this.count = Optional.ofNullable(count);
        return this;
    }


    /**
     * Number of transactions of this type
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCount(Optional<Long> count) {
        Utils.checkNotNull(count, "count");
        this.count = count;
        return this;
    }

    /**
     * Payment type of the transactions
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withMethod(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod method) {
        Utils.checkNotNull(method, "method");
        this.method = JsonNullable.of(method);
        return this;
    }

    /**
     * Payment type of the transactions
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withMethod(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod> method) {
        Utils.checkNotNull(method, "method");
        this.method = method;
        return this;
    }

    /**
     * In case of payments transactions with card, the card issuer will be available
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCardIssuer(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer cardIssuer) {
        Utils.checkNotNull(cardIssuer, "cardIssuer");
        this.cardIssuer = JsonNullable.of(cardIssuer);
        return this;
    }

    /**
     * In case of payments transactions with card, the card issuer will be available
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCardIssuer(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer> cardIssuer) {
        Utils.checkNotNull(cardIssuer, "cardIssuer");
        this.cardIssuer = cardIssuer;
        return this;
    }

    /**
     * In case of payments trnsactions with card, the card audience will be available.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCardAudience(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience cardAudience) {
        Utils.checkNotNull(cardAudience, "cardAudience");
        this.cardAudience = JsonNullable.of(cardAudience);
        return this;
    }

    /**
     * In case of payments trnsactions with card, the card audience will be available.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCardAudience(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience> cardAudience) {
        Utils.checkNotNull(cardAudience, "cardAudience");
        this.cardAudience = cardAudience;
        return this;
    }

    /**
     * In case of payments transactions with card, the card region will be available.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCardRegion(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion cardRegion) {
        Utils.checkNotNull(cardRegion, "cardRegion");
        this.cardRegion = JsonNullable.of(cardRegion);
        return this;
    }

    /**
     * In case of payments transactions with card, the card region will be available.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withCardRegion(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion> cardRegion) {
        Utils.checkNotNull(cardRegion, "cardRegion");
        this.cardRegion = cardRegion;
        return this;
    }

    /**
     * Present when the transaction represents a fee.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withFeeType(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType feeType) {
        Utils.checkNotNull(feeType, "feeType");
        this.feeType = JsonNullable.of(feeType);
        return this;
    }

    /**
     * Present when the transaction represents a fee.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withFeeType(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType> feeType) {
        Utils.checkNotNull(feeType, "feeType");
        this.feeType = feeType;
        return this;
    }

    /**
     * Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withPrepaymentPartType(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType prepaymentPartType) {
        Utils.checkNotNull(prepaymentPartType, "prepaymentPartType");
        this.prepaymentPartType = JsonNullable.of(prepaymentPartType);
        return this;
    }

    /**
     * Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withPrepaymentPartType(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType> prepaymentPartType) {
        Utils.checkNotNull(prepaymentPartType, "prepaymentPartType");
        this.prepaymentPartType = prepaymentPartType;
        return this;
    }

    /**
     * Represents the transaction type
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withTransactionType(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType transactionType) {
        Utils.checkNotNull(transactionType, "transactionType");
        this.transactionType = JsonNullable.of(transactionType);
        return this;
    }

    /**
     * Represents the transaction type
     */
    public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals withTransactionType(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType> transactionType) {
        Utils.checkNotNull(transactionType, "transactionType");
        this.transactionType = transactionType;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals other = (GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals) o;
        return 
            Utils.enhancedDeepEquals(this.count, other.count) &&
            Utils.enhancedDeepEquals(this.method, other.method) &&
            Utils.enhancedDeepEquals(this.cardIssuer, other.cardIssuer) &&
            Utils.enhancedDeepEquals(this.cardAudience, other.cardAudience) &&
            Utils.enhancedDeepEquals(this.cardRegion, other.cardRegion) &&
            Utils.enhancedDeepEquals(this.feeType, other.feeType) &&
            Utils.enhancedDeepEquals(this.prepaymentPartType, other.prepaymentPartType) &&
            Utils.enhancedDeepEquals(this.transactionType, other.transactionType);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            count, method, cardIssuer,
            cardAudience, cardRegion, feeType,
            prepaymentPartType, transactionType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals.class,
                "count", count,
                "method", method,
                "cardIssuer", cardIssuer,
                "cardAudience", cardAudience,
                "cardRegion", cardRegion,
                "feeType", feeType,
                "prepaymentPartType", prepaymentPartType,
                "transactionType", transactionType);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Long> count = Optional.empty();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod> method = JsonNullable.undefined();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer> cardIssuer = JsonNullable.undefined();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience> cardAudience = JsonNullable.undefined();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion> cardRegion = JsonNullable.undefined();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType> feeType = JsonNullable.undefined();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType> prepaymentPartType = JsonNullable.undefined();

        private JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType> transactionType = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Number of transactions of this type
         */
        public Builder count(long count) {
            Utils.checkNotNull(count, "count");
            this.count = Optional.ofNullable(count);
            return this;
        }

        /**
         * Number of transactions of this type
         */
        public Builder count(Optional<Long> count) {
            Utils.checkNotNull(count, "count");
            this.count = count;
            return this;
        }


        /**
         * Payment type of the transactions
         */
        public Builder method(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod method) {
            Utils.checkNotNull(method, "method");
            this.method = JsonNullable.of(method);
            return this;
        }

        /**
         * Payment type of the transactions
         */
        public Builder method(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingMethod> method) {
            Utils.checkNotNull(method, "method");
            this.method = method;
            return this;
        }


        /**
         * In case of payments transactions with card, the card issuer will be available
         */
        public Builder cardIssuer(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer cardIssuer) {
            Utils.checkNotNull(cardIssuer, "cardIssuer");
            this.cardIssuer = JsonNullable.of(cardIssuer);
            return this;
        }

        /**
         * In case of payments transactions with card, the card issuer will be available
         */
        public Builder cardIssuer(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardIssuer> cardIssuer) {
            Utils.checkNotNull(cardIssuer, "cardIssuer");
            this.cardIssuer = cardIssuer;
            return this;
        }


        /**
         * In case of payments trnsactions with card, the card audience will be available.
         */
        public Builder cardAudience(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience cardAudience) {
            Utils.checkNotNull(cardAudience, "cardAudience");
            this.cardAudience = JsonNullable.of(cardAudience);
            return this;
        }

        /**
         * In case of payments trnsactions with card, the card audience will be available.
         */
        public Builder cardAudience(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardAudience> cardAudience) {
            Utils.checkNotNull(cardAudience, "cardAudience");
            this.cardAudience = cardAudience;
            return this;
        }


        /**
         * In case of payments transactions with card, the card region will be available.
         */
        public Builder cardRegion(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion cardRegion) {
            Utils.checkNotNull(cardRegion, "cardRegion");
            this.cardRegion = JsonNullable.of(cardRegion);
            return this;
        }

        /**
         * In case of payments transactions with card, the card region will be available.
         */
        public Builder cardRegion(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingCardRegion> cardRegion) {
            Utils.checkNotNull(cardRegion, "cardRegion");
            this.cardRegion = cardRegion;
            return this;
        }


        /**
         * Present when the transaction represents a fee.
         */
        public Builder feeType(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType feeType) {
            Utils.checkNotNull(feeType, "feeType");
            this.feeType = JsonNullable.of(feeType);
            return this;
        }

        /**
         * Present when the transaction represents a fee.
         */
        public Builder feeType(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingFeeType> feeType) {
            Utils.checkNotNull(feeType, "feeType");
            this.feeType = feeType;
            return this;
        }


        /**
         * Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
         */
        public Builder prepaymentPartType(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType prepaymentPartType) {
            Utils.checkNotNull(prepaymentPartType, "prepaymentPartType");
            this.prepaymentPartType = JsonNullable.of(prepaymentPartType);
            return this;
        }

        /**
         * Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
         */
        public Builder prepaymentPartType(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingPrepaymentPartType> prepaymentPartType) {
            Utils.checkNotNull(prepaymentPartType, "prepaymentPartType");
            this.prepaymentPartType = prepaymentPartType;
            return this;
        }


        /**
         * Represents the transaction type
         */
        public Builder transactionType(GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType transactionType) {
            Utils.checkNotNull(transactionType, "transactionType");
            this.transactionType = JsonNullable.of(transactionType);
            return this;
        }

        /**
         * Represents the transaction type
         */
        public Builder transactionType(JsonNullable<? extends GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingTransactionType> transactionType) {
            Utils.checkNotNull(transactionType, "transactionType");
            this.transactionType = transactionType;
            return this;
        }

        public GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals build() {

            return new GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsChargebacksPendingSubTotals(
                count, method, cardIssuer,
                cardAudience, cardRegion, feeType,
                prepaymentPartType, transactionType);
        }

    }
}
