/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyCardIssuer
 * 
 * <p>In case of payments transactions with card, the card issuer will be available
 */
public enum GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyCardIssuer {
    AMEX("amex"),
    MAESTRO("maestro"),
    CARTE_BANCAIRE("carte-bancaire"),
    OTHER("other");

    @JsonValue
    private final String value;

    GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyCardIssuer(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyCardIssuer> fromValue(String value) {
        for (GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyCardIssuer o: GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyCardIssuer.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

