/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsTopupsCardRegion
 * 
 * <p>In case of payments transactions with card, the card region will be available.
 */
public enum GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsTopupsCardRegion {
    INTRA_EEA("intra-eea"),
    INTRA_EU("intra-eu"),
    DOMESTIC("domestic"),
    OTHER("other");

    @JsonValue
    private final String value;

    GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsTopupsCardRegion(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsTopupsCardRegion> fromValue(String value) {
        for (GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsTopupsCardRegion o: GetBalanceReportBalancesResponse200ApplicationHalPlusJsonResponseBodyTotalsTopupsCardRegion.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

