/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.mollie.mollie.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * GetChargebackLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */

public class GetChargebackLinks {

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("self")
    private Optional<? extends GetChargebackSelf> self;

    /**
     * The API resource URL of the [payment](get-payment) that this chargeback belongs to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment")
    private Optional<? extends GetChargebackPayment> payment;

    /**
     * The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement")
    private JsonNullable<? extends GetChargebackSettlement> settlement;

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documentation")
    private Optional<? extends GetChargebackDocumentation> documentation;

    @JsonCreator
    public GetChargebackLinks(
            @JsonProperty("self") Optional<? extends GetChargebackSelf> self,
            @JsonProperty("payment") Optional<? extends GetChargebackPayment> payment,
            @JsonProperty("settlement") JsonNullable<? extends GetChargebackSettlement> settlement,
            @JsonProperty("documentation") Optional<? extends GetChargebackDocumentation> documentation) {
        Utils.checkNotNull(self, "self");
        Utils.checkNotNull(payment, "payment");
        Utils.checkNotNull(settlement, "settlement");
        Utils.checkNotNull(documentation, "documentation");
        this.self = self;
        this.payment = payment;
        this.settlement = settlement;
        this.documentation = documentation;
    }
    
    public GetChargebackLinks() {
        this(Optional.empty(), Optional.empty(), JsonNullable.undefined(), Optional.empty());
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetChargebackSelf> self() {
        return (Optional<GetChargebackSelf>) self;
    }

    /**
     * The API resource URL of the [payment](get-payment) that this chargeback belongs to.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetChargebackPayment> payment() {
        return (Optional<GetChargebackPayment>) payment;
    }

    /**
     * The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<GetChargebackSettlement> settlement() {
        return (JsonNullable<GetChargebackSettlement>) settlement;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetChargebackDocumentation> documentation() {
        return (Optional<GetChargebackDocumentation>) documentation;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public GetChargebackLinks withSelf(GetChargebackSelf self) {
        Utils.checkNotNull(self, "self");
        this.self = Optional.ofNullable(self);
        return this;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public GetChargebackLinks withSelf(Optional<? extends GetChargebackSelf> self) {
        Utils.checkNotNull(self, "self");
        this.self = self;
        return this;
    }

    /**
     * The API resource URL of the [payment](get-payment) that this chargeback belongs to.
     */
    public GetChargebackLinks withPayment(GetChargebackPayment payment) {
        Utils.checkNotNull(payment, "payment");
        this.payment = Optional.ofNullable(payment);
        return this;
    }

    /**
     * The API resource URL of the [payment](get-payment) that this chargeback belongs to.
     */
    public GetChargebackLinks withPayment(Optional<? extends GetChargebackPayment> payment) {
        Utils.checkNotNull(payment, "payment");
        this.payment = payment;
        return this;
    }

    /**
     * The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
     */
    public GetChargebackLinks withSettlement(GetChargebackSettlement settlement) {
        Utils.checkNotNull(settlement, "settlement");
        this.settlement = JsonNullable.of(settlement);
        return this;
    }

    /**
     * The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
     */
    public GetChargebackLinks withSettlement(JsonNullable<? extends GetChargebackSettlement> settlement) {
        Utils.checkNotNull(settlement, "settlement");
        this.settlement = settlement;
        return this;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public GetChargebackLinks withDocumentation(GetChargebackDocumentation documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = Optional.ofNullable(documentation);
        return this;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public GetChargebackLinks withDocumentation(Optional<? extends GetChargebackDocumentation> documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetChargebackLinks other = (GetChargebackLinks) o;
        return 
            Objects.deepEquals(this.self, other.self) &&
            Objects.deepEquals(this.payment, other.payment) &&
            Objects.deepEquals(this.settlement, other.settlement) &&
            Objects.deepEquals(this.documentation, other.documentation);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            self,
            payment,
            settlement,
            documentation);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetChargebackLinks.class,
                "self", self,
                "payment", payment,
                "settlement", settlement,
                "documentation", documentation);
    }
    
    public final static class Builder {
 
        private Optional<? extends GetChargebackSelf> self = Optional.empty();
 
        private Optional<? extends GetChargebackPayment> payment = Optional.empty();
 
        private JsonNullable<? extends GetChargebackSettlement> settlement = JsonNullable.undefined();
 
        private Optional<? extends GetChargebackDocumentation> documentation = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder self(GetChargebackSelf self) {
            Utils.checkNotNull(self, "self");
            this.self = Optional.ofNullable(self);
            return this;
        }

        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder self(Optional<? extends GetChargebackSelf> self) {
            Utils.checkNotNull(self, "self");
            this.self = self;
            return this;
        }

        /**
         * The API resource URL of the [payment](get-payment) that this chargeback belongs to.
         */
        public Builder payment(GetChargebackPayment payment) {
            Utils.checkNotNull(payment, "payment");
            this.payment = Optional.ofNullable(payment);
            return this;
        }

        /**
         * The API resource URL of the [payment](get-payment) that this chargeback belongs to.
         */
        public Builder payment(Optional<? extends GetChargebackPayment> payment) {
            Utils.checkNotNull(payment, "payment");
            this.payment = payment;
            return this;
        }

        /**
         * The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
         */
        public Builder settlement(GetChargebackSettlement settlement) {
            Utils.checkNotNull(settlement, "settlement");
            this.settlement = JsonNullable.of(settlement);
            return this;
        }

        /**
         * The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
         */
        public Builder settlement(JsonNullable<? extends GetChargebackSettlement> settlement) {
            Utils.checkNotNull(settlement, "settlement");
            this.settlement = settlement;
            return this;
        }

        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder documentation(GetChargebackDocumentation documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = Optional.ofNullable(documentation);
            return this;
        }

        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder documentation(Optional<? extends GetChargebackDocumentation> documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = documentation;
            return this;
        }
        
        public GetChargebackLinks build() {
            return new GetChargebackLinks(
                self,
                payment,
                settlement,
                documentation);
        }
    }
}

