/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

/**
 * GetMethodSelf
 * 
 * <p>In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
 */
public class GetMethodSelf {

    /**
     * The actual URL string.
     */
    @JsonProperty("href")
    private String href;

    /**
     * The content type of the page or endpoint the URL points to.
     */
    @JsonProperty("type")
    private String type;

    @JsonCreator
    public GetMethodSelf(
            @JsonProperty("href") String href,
            @JsonProperty("type") String type) {
        Utils.checkNotNull(href, "href");
        Utils.checkNotNull(type, "type");
        this.href = href;
        this.type = type;
    }

    /**
     * The actual URL string.
     */
    @JsonIgnore
    public String href() {
        return href;
    }

    /**
     * The content type of the page or endpoint the URL points to.
     */
    @JsonIgnore
    public String type() {
        return type;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The actual URL string.
     */
    public GetMethodSelf withHref(String href) {
        Utils.checkNotNull(href, "href");
        this.href = href;
        return this;
    }

    /**
     * The content type of the page or endpoint the URL points to.
     */
    public GetMethodSelf withType(String type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetMethodSelf other = (GetMethodSelf) o;
        return 
            Objects.deepEquals(this.href, other.href) &&
            Objects.deepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            href,
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetMethodSelf.class,
                "href", href,
                "type", type);
    }
    
    public final static class Builder {
 
        private String href;
 
        private String type;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The actual URL string.
         */
        public Builder href(String href) {
            Utils.checkNotNull(href, "href");
            this.href = href;
            return this;
        }

        /**
         * The content type of the page or endpoint the URL points to.
         */
        public Builder type(String type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }
        
        public GetMethodSelf build() {
            return new GetMethodSelf(
                href,
                type);
        }
    }
}
