/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

public class GetNextSettlementLessThanYearGreaterThan {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("<month>")
    private Optional<? extends GetNextSettlementLessThanMonthGreaterThan> lessThanMonthGreaterThan;

    @JsonCreator
    public GetNextSettlementLessThanYearGreaterThan(
            @JsonProperty("<month>") Optional<? extends GetNextSettlementLessThanMonthGreaterThan> lessThanMonthGreaterThan) {
        Utils.checkNotNull(lessThanMonthGreaterThan, "lessThanMonthGreaterThan");
        this.lessThanMonthGreaterThan = lessThanMonthGreaterThan;
    }
    
    public GetNextSettlementLessThanYearGreaterThan() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetNextSettlementLessThanMonthGreaterThan> lessThanMonthGreaterThan() {
        return (Optional<GetNextSettlementLessThanMonthGreaterThan>) lessThanMonthGreaterThan;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public GetNextSettlementLessThanYearGreaterThan withLessThanMonthGreaterThan(GetNextSettlementLessThanMonthGreaterThan lessThanMonthGreaterThan) {
        Utils.checkNotNull(lessThanMonthGreaterThan, "lessThanMonthGreaterThan");
        this.lessThanMonthGreaterThan = Optional.ofNullable(lessThanMonthGreaterThan);
        return this;
    }

    public GetNextSettlementLessThanYearGreaterThan withLessThanMonthGreaterThan(Optional<? extends GetNextSettlementLessThanMonthGreaterThan> lessThanMonthGreaterThan) {
        Utils.checkNotNull(lessThanMonthGreaterThan, "lessThanMonthGreaterThan");
        this.lessThanMonthGreaterThan = lessThanMonthGreaterThan;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetNextSettlementLessThanYearGreaterThan other = (GetNextSettlementLessThanYearGreaterThan) o;
        return 
            Utils.enhancedDeepEquals(this.lessThanMonthGreaterThan, other.lessThanMonthGreaterThan);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            lessThanMonthGreaterThan);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetNextSettlementLessThanYearGreaterThan.class,
                "lessThanMonthGreaterThan", lessThanMonthGreaterThan);
    }
    
    public final static class Builder {
 
        private Optional<? extends GetNextSettlementLessThanMonthGreaterThan> lessThanMonthGreaterThan = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder lessThanMonthGreaterThan(GetNextSettlementLessThanMonthGreaterThan lessThanMonthGreaterThan) {
            Utils.checkNotNull(lessThanMonthGreaterThan, "lessThanMonthGreaterThan");
            this.lessThanMonthGreaterThan = Optional.ofNullable(lessThanMonthGreaterThan);
            return this;
        }

        public Builder lessThanMonthGreaterThan(Optional<? extends GetNextSettlementLessThanMonthGreaterThan> lessThanMonthGreaterThan) {
            Utils.checkNotNull(lessThanMonthGreaterThan, "lessThanMonthGreaterThan");
            this.lessThanMonthGreaterThan = lessThanMonthGreaterThan;
            return this;
        }
        
        public GetNextSettlementLessThanYearGreaterThan build() {
            return new GetNextSettlementLessThanYearGreaterThan(
                lessThanMonthGreaterThan);
        }
    }
}
