/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetPaymentLinkPaymentsCardLabel
 * 
 * <p>The card's label, if known.
 */
public enum GetPaymentLinkPaymentsCardLabel {
    AMERICAN_EXPRESS("American Express"),
    CARTA_SI("Carta Si"),
    CARTE_BLEUE("Carte Bleue"),
    DANKORT("Dankort"),
    DINERS_CLUB("Diners Club"),
    DISCOVER("Discover"),
    JCB("JCB"),
    LASER("Laser"),
    MAESTRO("Maestro"),
    MASTERCARD("Mastercard"),
    UNIONPAY("Unionpay"),
    VISA("Visa"),
    VPAY("Vpay");

    @JsonValue
    private final String value;

    GetPaymentLinkPaymentsCardLabel(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetPaymentLinkPaymentsCardLabel> fromValue(String value) {
        for (GetPaymentLinkPaymentsCardLabel o: GetPaymentLinkPaymentsCardLabel.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

