/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetPrimaryBalanceCurrency
 * 
 * <p>The balance's ISO 4217 currency code.
 */
public enum GetPrimaryBalanceCurrency {
    EUR("EUR"),
    GBP("GBP"),
    CHF("CHF"),
    DKK("DKK"),
    NOK("NOK"),
    PLN("PLN"),
    SEK("SEK"),
    USD("USD"),
    CZK("CZK"),
    HUF("HUF"),
    AUD("AUD"),
    CAD("CAD");

    @JsonValue
    private final String value;

    private GetPrimaryBalanceCurrency(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetPrimaryBalanceCurrency> fromValue(String value) {
        for (GetPrimaryBalanceCurrency o: GetPrimaryBalanceCurrency.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

