/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.mollie.mollie.utils.LazySingletonValue;
import com.mollie.mollie.utils.Utils;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class ListSubscriptionsRequestBuilder {

    private String customerId;
    private Optional<String> from = Optional.empty();
    private JsonNullable<Long> limit = Utils.readDefaultOrConstValue(
                            "limit",
                            "50",
                            new TypeReference<JsonNullable<Long>>() {});
    private JsonNullable<Boolean> testmode = Utils.readDefaultOrConstValue(
                            "testmode",
                            "false",
                            new TypeReference<JsonNullable<Boolean>>() {});
    private final SDKMethodInterfaces.MethodCallListSubscriptions sdk;

    public ListSubscriptionsRequestBuilder(SDKMethodInterfaces.MethodCallListSubscriptions sdk) {
        this.sdk = sdk;
    }

    public ListSubscriptionsRequestBuilder customerId(String customerId) {
        Utils.checkNotNull(customerId, "customerId");
        this.customerId = customerId;
        return this;
    }
                
    public ListSubscriptionsRequestBuilder from(String from) {
        Utils.checkNotNull(from, "from");
        this.from = Optional.of(from);
        return this;
    }

    public ListSubscriptionsRequestBuilder from(Optional<String> from) {
        Utils.checkNotNull(from, "from");
        this.from = from;
        return this;
    }

    public ListSubscriptionsRequestBuilder limit(long limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = JsonNullable.of(limit);
        return this;
    }

    public ListSubscriptionsRequestBuilder limit(JsonNullable<Long> limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = limit;
        return this;
    }

    public ListSubscriptionsRequestBuilder testmode(boolean testmode) {
        Utils.checkNotNull(testmode, "testmode");
        this.testmode = JsonNullable.of(testmode);
        return this;
    }

    public ListSubscriptionsRequestBuilder testmode(JsonNullable<Boolean> testmode) {
        Utils.checkNotNull(testmode, "testmode");
        this.testmode = testmode;
        return this;
    }

    public ListSubscriptionsResponse call() throws Exception {
        if (limit == null) {
            limit = _SINGLETON_VALUE_Limit.value();
        }
        if (testmode == null) {
            testmode = _SINGLETON_VALUE_Testmode.value();
        }
        return sdk.listSubscriptions(
            customerId,
            from,
            limit,
            testmode);
    }

    private static final LazySingletonValue<JsonNullable<Long>> _SINGLETON_VALUE_Limit =
            new LazySingletonValue<>(
                    "limit",
                    "50",
                    new TypeReference<JsonNullable<Long>>() {});

    private static final LazySingletonValue<JsonNullable<Boolean>> _SINGLETON_VALUE_Testmode =
            new LazySingletonValue<>(
                    "testmode",
                    "false",
                    new TypeReference<JsonNullable<Boolean>>() {});
}
