/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.mollie.mollie.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class ListPaymentLinksEmbedded {

    /**
     * An array of payment link objects. For a complete reference of the payment link object, refer to
     * the [Get payment link endpoint](get-payment-link) documentation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_links")
    private Optional<? extends List<PaymentLinks>> paymentLinks;

    @JsonCreator
    public ListPaymentLinksEmbedded(
            @JsonProperty("payment_links") Optional<? extends List<PaymentLinks>> paymentLinks) {
        Utils.checkNotNull(paymentLinks, "paymentLinks");
        this.paymentLinks = paymentLinks;
    }
    
    public ListPaymentLinksEmbedded() {
        this(Optional.empty());
    }

    /**
     * An array of payment link objects. For a complete reference of the payment link object, refer to
     * the [Get payment link endpoint](get-payment-link) documentation.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<PaymentLinks>> paymentLinks() {
        return (Optional<List<PaymentLinks>>) paymentLinks;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * An array of payment link objects. For a complete reference of the payment link object, refer to
     * the [Get payment link endpoint](get-payment-link) documentation.
     */
    public ListPaymentLinksEmbedded withPaymentLinks(List<PaymentLinks> paymentLinks) {
        Utils.checkNotNull(paymentLinks, "paymentLinks");
        this.paymentLinks = Optional.ofNullable(paymentLinks);
        return this;
    }

    /**
     * An array of payment link objects. For a complete reference of the payment link object, refer to
     * the [Get payment link endpoint](get-payment-link) documentation.
     */
    public ListPaymentLinksEmbedded withPaymentLinks(Optional<? extends List<PaymentLinks>> paymentLinks) {
        Utils.checkNotNull(paymentLinks, "paymentLinks");
        this.paymentLinks = paymentLinks;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListPaymentLinksEmbedded other = (ListPaymentLinksEmbedded) o;
        return 
            Objects.deepEquals(this.paymentLinks, other.paymentLinks);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            paymentLinks);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListPaymentLinksEmbedded.class,
                "paymentLinks", paymentLinks);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<PaymentLinks>> paymentLinks = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * An array of payment link objects. For a complete reference of the payment link object, refer to
         * the [Get payment link endpoint](get-payment-link) documentation.
         */
        public Builder paymentLinks(List<PaymentLinks> paymentLinks) {
            Utils.checkNotNull(paymentLinks, "paymentLinks");
            this.paymentLinks = Optional.ofNullable(paymentLinks);
            return this;
        }

        /**
         * An array of payment link objects. For a complete reference of the payment link object, refer to
         * the [Get payment link endpoint](get-payment-link) documentation.
         */
        public Builder paymentLinks(Optional<? extends List<PaymentLinks>> paymentLinks) {
            Utils.checkNotNull(paymentLinks, "paymentLinks");
            this.paymentLinks = paymentLinks;
            return this;
        }
        
        public ListPaymentLinksEmbedded build() {
            return new ListPaymentLinksEmbedded(
                paymentLinks);
        }
    }
}

