/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * ListSubscriptionsSubscriptionsLinks
 * 
 * <p>An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */
public class ListSubscriptionsSubscriptionsLinks {
    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("self")
    private Optional<? extends ListSubscriptionsSubscriptionsSelf> self;

    /**
     * The API resource URL of the [customer](get-customer) this subscription was created for.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer")
    private JsonNullable<? extends ListSubscriptionsCustomer> customer;

    /**
     * The API resource URL of the [mandate](get-mandate) this subscription was created for.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mandate")
    private JsonNullable<? extends ListSubscriptionsMandate> mandate;

    /**
     * The API resource URL of the [profile](get-profile) this subscription was created for.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profile")
    private JsonNullable<? extends ListSubscriptionsProfile> profile;

    /**
     * The API resource URL of the [payments](list-payments) created for this subscription. Omitted if no such
     * payments exist (yet).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payments")
    private JsonNullable<? extends ListSubscriptionsPayments> payments;

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documentation")
    private Optional<? extends ListSubscriptionsSubscriptionsDocumentation> documentation;

    @JsonCreator
    public ListSubscriptionsSubscriptionsLinks(
            @JsonProperty("self") Optional<? extends ListSubscriptionsSubscriptionsSelf> self,
            @JsonProperty("customer") JsonNullable<? extends ListSubscriptionsCustomer> customer,
            @JsonProperty("mandate") JsonNullable<? extends ListSubscriptionsMandate> mandate,
            @JsonProperty("profile") JsonNullable<? extends ListSubscriptionsProfile> profile,
            @JsonProperty("payments") JsonNullable<? extends ListSubscriptionsPayments> payments,
            @JsonProperty("documentation") Optional<? extends ListSubscriptionsSubscriptionsDocumentation> documentation) {
        Utils.checkNotNull(self, "self");
        Utils.checkNotNull(customer, "customer");
        Utils.checkNotNull(mandate, "mandate");
        Utils.checkNotNull(profile, "profile");
        Utils.checkNotNull(payments, "payments");
        Utils.checkNotNull(documentation, "documentation");
        this.self = self;
        this.customer = customer;
        this.mandate = mandate;
        this.profile = profile;
        this.payments = payments;
        this.documentation = documentation;
    }
    
    public ListSubscriptionsSubscriptionsLinks() {
        this(Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty());
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ListSubscriptionsSubscriptionsSelf> self() {
        return (Optional<ListSubscriptionsSubscriptionsSelf>) self;
    }

    /**
     * The API resource URL of the [customer](get-customer) this subscription was created for.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<ListSubscriptionsCustomer> customer() {
        return (JsonNullable<ListSubscriptionsCustomer>) customer;
    }

    /**
     * The API resource URL of the [mandate](get-mandate) this subscription was created for.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<ListSubscriptionsMandate> mandate() {
        return (JsonNullable<ListSubscriptionsMandate>) mandate;
    }

    /**
     * The API resource URL of the [profile](get-profile) this subscription was created for.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<ListSubscriptionsProfile> profile() {
        return (JsonNullable<ListSubscriptionsProfile>) profile;
    }

    /**
     * The API resource URL of the [payments](list-payments) created for this subscription. Omitted if no such
     * payments exist (yet).
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<ListSubscriptionsPayments> payments() {
        return (JsonNullable<ListSubscriptionsPayments>) payments;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ListSubscriptionsSubscriptionsDocumentation> documentation() {
        return (Optional<ListSubscriptionsSubscriptionsDocumentation>) documentation;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public ListSubscriptionsSubscriptionsLinks withSelf(ListSubscriptionsSubscriptionsSelf self) {
        Utils.checkNotNull(self, "self");
        this.self = Optional.ofNullable(self);
        return this;
    }


    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public ListSubscriptionsSubscriptionsLinks withSelf(Optional<? extends ListSubscriptionsSubscriptionsSelf> self) {
        Utils.checkNotNull(self, "self");
        this.self = self;
        return this;
    }

    /**
     * The API resource URL of the [customer](get-customer) this subscription was created for.
     */
    public ListSubscriptionsSubscriptionsLinks withCustomer(ListSubscriptionsCustomer customer) {
        Utils.checkNotNull(customer, "customer");
        this.customer = JsonNullable.of(customer);
        return this;
    }

    /**
     * The API resource URL of the [customer](get-customer) this subscription was created for.
     */
    public ListSubscriptionsSubscriptionsLinks withCustomer(JsonNullable<? extends ListSubscriptionsCustomer> customer) {
        Utils.checkNotNull(customer, "customer");
        this.customer = customer;
        return this;
    }

    /**
     * The API resource URL of the [mandate](get-mandate) this subscription was created for.
     */
    public ListSubscriptionsSubscriptionsLinks withMandate(ListSubscriptionsMandate mandate) {
        Utils.checkNotNull(mandate, "mandate");
        this.mandate = JsonNullable.of(mandate);
        return this;
    }

    /**
     * The API resource URL of the [mandate](get-mandate) this subscription was created for.
     */
    public ListSubscriptionsSubscriptionsLinks withMandate(JsonNullable<? extends ListSubscriptionsMandate> mandate) {
        Utils.checkNotNull(mandate, "mandate");
        this.mandate = mandate;
        return this;
    }

    /**
     * The API resource URL of the [profile](get-profile) this subscription was created for.
     */
    public ListSubscriptionsSubscriptionsLinks withProfile(ListSubscriptionsProfile profile) {
        Utils.checkNotNull(profile, "profile");
        this.profile = JsonNullable.of(profile);
        return this;
    }

    /**
     * The API resource URL of the [profile](get-profile) this subscription was created for.
     */
    public ListSubscriptionsSubscriptionsLinks withProfile(JsonNullable<? extends ListSubscriptionsProfile> profile) {
        Utils.checkNotNull(profile, "profile");
        this.profile = profile;
        return this;
    }

    /**
     * The API resource URL of the [payments](list-payments) created for this subscription. Omitted if no such
     * payments exist (yet).
     */
    public ListSubscriptionsSubscriptionsLinks withPayments(ListSubscriptionsPayments payments) {
        Utils.checkNotNull(payments, "payments");
        this.payments = JsonNullable.of(payments);
        return this;
    }

    /**
     * The API resource URL of the [payments](list-payments) created for this subscription. Omitted if no such
     * payments exist (yet).
     */
    public ListSubscriptionsSubscriptionsLinks withPayments(JsonNullable<? extends ListSubscriptionsPayments> payments) {
        Utils.checkNotNull(payments, "payments");
        this.payments = payments;
        return this;
    }

    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public ListSubscriptionsSubscriptionsLinks withDocumentation(ListSubscriptionsSubscriptionsDocumentation documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = Optional.ofNullable(documentation);
        return this;
    }


    /**
     * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
     */
    public ListSubscriptionsSubscriptionsLinks withDocumentation(Optional<? extends ListSubscriptionsSubscriptionsDocumentation> documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListSubscriptionsSubscriptionsLinks other = (ListSubscriptionsSubscriptionsLinks) o;
        return 
            Utils.enhancedDeepEquals(this.self, other.self) &&
            Utils.enhancedDeepEquals(this.customer, other.customer) &&
            Utils.enhancedDeepEquals(this.mandate, other.mandate) &&
            Utils.enhancedDeepEquals(this.profile, other.profile) &&
            Utils.enhancedDeepEquals(this.payments, other.payments) &&
            Utils.enhancedDeepEquals(this.documentation, other.documentation);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            self, customer, mandate,
            profile, payments, documentation);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListSubscriptionsSubscriptionsLinks.class,
                "self", self,
                "customer", customer,
                "mandate", mandate,
                "profile", profile,
                "payments", payments,
                "documentation", documentation);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends ListSubscriptionsSubscriptionsSelf> self = Optional.empty();

        private JsonNullable<? extends ListSubscriptionsCustomer> customer = JsonNullable.undefined();

        private JsonNullable<? extends ListSubscriptionsMandate> mandate = JsonNullable.undefined();

        private JsonNullable<? extends ListSubscriptionsProfile> profile = JsonNullable.undefined();

        private JsonNullable<? extends ListSubscriptionsPayments> payments = JsonNullable.undefined();

        private Optional<? extends ListSubscriptionsSubscriptionsDocumentation> documentation = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder self(ListSubscriptionsSubscriptionsSelf self) {
            Utils.checkNotNull(self, "self");
            this.self = Optional.ofNullable(self);
            return this;
        }

        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder self(Optional<? extends ListSubscriptionsSubscriptionsSelf> self) {
            Utils.checkNotNull(self, "self");
            this.self = self;
            return this;
        }


        /**
         * The API resource URL of the [customer](get-customer) this subscription was created for.
         */
        public Builder customer(ListSubscriptionsCustomer customer) {
            Utils.checkNotNull(customer, "customer");
            this.customer = JsonNullable.of(customer);
            return this;
        }

        /**
         * The API resource URL of the [customer](get-customer) this subscription was created for.
         */
        public Builder customer(JsonNullable<? extends ListSubscriptionsCustomer> customer) {
            Utils.checkNotNull(customer, "customer");
            this.customer = customer;
            return this;
        }


        /**
         * The API resource URL of the [mandate](get-mandate) this subscription was created for.
         */
        public Builder mandate(ListSubscriptionsMandate mandate) {
            Utils.checkNotNull(mandate, "mandate");
            this.mandate = JsonNullable.of(mandate);
            return this;
        }

        /**
         * The API resource URL of the [mandate](get-mandate) this subscription was created for.
         */
        public Builder mandate(JsonNullable<? extends ListSubscriptionsMandate> mandate) {
            Utils.checkNotNull(mandate, "mandate");
            this.mandate = mandate;
            return this;
        }


        /**
         * The API resource URL of the [profile](get-profile) this subscription was created for.
         */
        public Builder profile(ListSubscriptionsProfile profile) {
            Utils.checkNotNull(profile, "profile");
            this.profile = JsonNullable.of(profile);
            return this;
        }

        /**
         * The API resource URL of the [profile](get-profile) this subscription was created for.
         */
        public Builder profile(JsonNullable<? extends ListSubscriptionsProfile> profile) {
            Utils.checkNotNull(profile, "profile");
            this.profile = profile;
            return this;
        }


        /**
         * The API resource URL of the [payments](list-payments) created for this subscription. Omitted if no such
         * payments exist (yet).
         */
        public Builder payments(ListSubscriptionsPayments payments) {
            Utils.checkNotNull(payments, "payments");
            this.payments = JsonNullable.of(payments);
            return this;
        }

        /**
         * The API resource URL of the [payments](list-payments) created for this subscription. Omitted if no such
         * payments exist (yet).
         */
        public Builder payments(JsonNullable<? extends ListSubscriptionsPayments> payments) {
            Utils.checkNotNull(payments, "payments");
            this.payments = payments;
            return this;
        }


        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder documentation(ListSubscriptionsSubscriptionsDocumentation documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = Optional.ofNullable(documentation);
            return this;
        }

        /**
         * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
         */
        public Builder documentation(Optional<? extends ListSubscriptionsSubscriptionsDocumentation> documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = documentation;
            return this;
        }

        public ListSubscriptionsSubscriptionsLinks build() {

            return new ListSubscriptionsSubscriptionsLinks(
                self, customer, mandate,
                profile, payments, documentation);
        }

    }
}
