/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ListAllChargebacksQueryParamSort
 * 
 * <p>Used for setting the direction of the result set. Defaults to descending order, meaning the results are ordered from
 * newest to oldest.
 */
public enum ListAllChargebacksQueryParamSort {
    ASC("asc"),
    DESC("desc");

    @JsonValue
    private final String value;

    ListAllChargebacksQueryParamSort(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ListAllChargebacksQueryParamSort> fromValue(String value) {
        for (ListAllChargebacksQueryParamSort o: ListAllChargebacksQueryParamSort.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

