/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cbb18aa84b0e
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;

/**
 * ListBusinessAccountsResponseBody
 * 
 * <p>A list of business account objects.
 */
public class ListBusinessAccountsResponseBody {
    /**
     * The number of items in this result set. If more items are available, a `_links.next` URL will be
     * present in the result
     * as well.
     * 
     * <p>The maximum number of items per result set is controlled by the `limit` property provided in the
     * request. The default
     * limit is 50 items.
     */
    @JsonProperty("count")
    private long count;


    @JsonProperty("_embedded")
    private ListBusinessAccountsEmbedded embedded;

    @JsonCreator
    public ListBusinessAccountsResponseBody(
            @JsonProperty("count") long count,
            @JsonProperty("_embedded") ListBusinessAccountsEmbedded embedded) {
        Utils.checkNotNull(count, "count");
        Utils.checkNotNull(embedded, "embedded");
        this.count = count;
        this.embedded = embedded;
    }

    /**
     * The number of items in this result set. If more items are available, a `_links.next` URL will be
     * present in the result
     * as well.
     * 
     * <p>The maximum number of items per result set is controlled by the `limit` property provided in the
     * request. The default
     * limit is 50 items.
     */
    @JsonIgnore
    public long count() {
        return count;
    }

    @JsonIgnore
    public ListBusinessAccountsEmbedded embedded() {
        return embedded;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The number of items in this result set. If more items are available, a `_links.next` URL will be
     * present in the result
     * as well.
     * 
     * <p>The maximum number of items per result set is controlled by the `limit` property provided in the
     * request. The default
     * limit is 50 items.
     */
    public ListBusinessAccountsResponseBody withCount(long count) {
        Utils.checkNotNull(count, "count");
        this.count = count;
        return this;
    }

    public ListBusinessAccountsResponseBody withEmbedded(ListBusinessAccountsEmbedded embedded) {
        Utils.checkNotNull(embedded, "embedded");
        this.embedded = embedded;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListBusinessAccountsResponseBody other = (ListBusinessAccountsResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.count, other.count) &&
            Utils.enhancedDeepEquals(this.embedded, other.embedded);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            count, embedded);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListBusinessAccountsResponseBody.class,
                "count", count,
                "embedded", embedded);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long count;

        private ListBusinessAccountsEmbedded embedded;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The number of items in this result set. If more items are available, a `_links.next` URL will be
         * present in the result
         * as well.
         * 
         * <p>The maximum number of items per result set is controlled by the `limit` property provided in the
         * request. The default
         * limit is 50 items.
         */
        public Builder count(long count) {
            Utils.checkNotNull(count, "count");
            this.count = count;
            return this;
        }


        public Builder embedded(ListBusinessAccountsEmbedded embedded) {
            Utils.checkNotNull(embedded, "embedded");
            this.embedded = embedded;
            return this;
        }

        public ListBusinessAccountsResponseBody build() {

            return new ListBusinessAccountsResponseBody(
                count, embedded);
        }

    }
}
