/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ListSalesInvoicesSource
 * 
 * <p>The way through which the invoice is to be set to paid.
 */
public enum ListSalesInvoicesSource {
    MANUAL("manual"),
    PAYMENT_LINK("payment-link"),
    PAYMENT("payment");

    @JsonValue
    private final String value;

    ListSalesInvoicesSource(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ListSalesInvoicesSource> fromValue(String value) {
        for (ListSalesInvoicesSource o: ListSalesInvoicesSource.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

