/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.io.InputStream;
import java.lang.Long;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateCustomerPaymentCustomersResponseBody
 * 
 * <p>An error response object.
 */
@SuppressWarnings("serial")
public class CreateCustomerPaymentCustomersResponseBody extends RuntimeException {

    /**
     * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
     */
    @JsonProperty("status")
    private long status;

    /**
     * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
     */
    @JsonProperty("title")
    private String title;

    /**
     * A detailed human-readable description of the error that occurred.
     */
    @JsonProperty("detail")
    private String detail;

    /**
     * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("field")
    private Optional<String> field;

    @JsonProperty("_links")
    private CreateCustomerPaymentCustomersLinks links;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("RawResponse")
    private Optional<? extends HttpResponse<InputStream>> rawResponse;

    @JsonCreator
    public CreateCustomerPaymentCustomersResponseBody(
            @JsonProperty("status") long status,
            @JsonProperty("title") String title,
            @JsonProperty("detail") String detail,
            @JsonProperty("field") Optional<String> field,
            @JsonProperty("_links") CreateCustomerPaymentCustomersLinks links,
            @JsonProperty("RawResponse") Optional<? extends HttpResponse<InputStream>> rawResponse) {
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(detail, "detail");
        Utils.checkNotNull(field, "field");
        Utils.checkNotNull(links, "links");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.status = status;
        this.title = title;
        this.detail = detail;
        this.field = field;
        this.links = links;
        this.rawResponse = rawResponse;
    }
    
    public CreateCustomerPaymentCustomersResponseBody(
            long status,
            String title,
            String detail,
            CreateCustomerPaymentCustomersLinks links) {
        this(status, title, detail, Optional.empty(), links, Optional.empty());
    }

    /**
     * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
     */
    @JsonIgnore
    public long status() {
        return status;
    }

    /**
     * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
     */
    @JsonIgnore
    public String title() {
        return title;
    }

    /**
     * A detailed human-readable description of the error that occurred.
     */
    @JsonIgnore
    public String detail() {
        return detail;
    }

    /**
     * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
     */
    @JsonIgnore
    public Optional<String> field() {
        return field;
    }

    @JsonIgnore
    public CreateCustomerPaymentCustomersLinks links() {
        return links;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<HttpResponse<InputStream>> rawResponse() {
        return (Optional<HttpResponse<InputStream>>) rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
     */
    public CreateCustomerPaymentCustomersResponseBody withStatus(long status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    /**
     * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
     */
    public CreateCustomerPaymentCustomersResponseBody withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    /**
     * A detailed human-readable description of the error that occurred.
     */
    public CreateCustomerPaymentCustomersResponseBody withDetail(String detail) {
        Utils.checkNotNull(detail, "detail");
        this.detail = detail;
        return this;
    }

    /**
     * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
     */
    public CreateCustomerPaymentCustomersResponseBody withField(String field) {
        Utils.checkNotNull(field, "field");
        this.field = Optional.ofNullable(field);
        return this;
    }

    /**
     * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
     */
    public CreateCustomerPaymentCustomersResponseBody withField(Optional<String> field) {
        Utils.checkNotNull(field, "field");
        this.field = field;
        return this;
    }

    public CreateCustomerPaymentCustomersResponseBody withLinks(CreateCustomerPaymentCustomersLinks links) {
        Utils.checkNotNull(links, "links");
        this.links = links;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateCustomerPaymentCustomersResponseBody withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = Optional.ofNullable(rawResponse);
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateCustomerPaymentCustomersResponseBody withRawResponse(Optional<? extends HttpResponse<InputStream>> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateCustomerPaymentCustomersResponseBody other = (CreateCustomerPaymentCustomersResponseBody) o;
        return 
            Objects.deepEquals(this.status, other.status) &&
            Objects.deepEquals(this.title, other.title) &&
            Objects.deepEquals(this.detail, other.detail) &&
            Objects.deepEquals(this.field, other.field) &&
            Objects.deepEquals(this.links, other.links) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            status,
            title,
            detail,
            field,
            links,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateCustomerPaymentCustomersResponseBody.class,
                "status", status,
                "title", title,
                "detail", detail,
                "field", field,
                "links", links,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private Long status;
 
        private String title;
 
        private String detail;
 
        private Optional<String> field = Optional.empty();
 
        private CreateCustomerPaymentCustomersLinks links;
 
        private Optional<? extends HttpResponse<InputStream>> rawResponse;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
         */
        public Builder status(long status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }

        /**
         * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
         */
        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }

        /**
         * A detailed human-readable description of the error that occurred.
         */
        public Builder detail(String detail) {
            Utils.checkNotNull(detail, "detail");
            this.detail = detail;
            return this;
        }

        /**
         * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
         */
        public Builder field(String field) {
            Utils.checkNotNull(field, "field");
            this.field = Optional.ofNullable(field);
            return this;
        }

        /**
         * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
         */
        public Builder field(Optional<String> field) {
            Utils.checkNotNull(field, "field");
            this.field = field;
            return this;
        }

        public Builder links(CreateCustomerPaymentCustomersLinks links) {
            Utils.checkNotNull(links, "links");
            this.links = links;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = Optional.ofNullable(rawResponse);
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(Optional<? extends HttpResponse<InputStream>> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public CreateCustomerPaymentCustomersResponseBody build() {
            return new CreateCustomerPaymentCustomersResponseBody(
                status,
                title,
                detail,
                field,
                links,
                rawResponse);
        }
    }
}

