/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

public class DeleteCustomerLinks {

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documentation")
    private Optional<? extends DeleteCustomerDocumentation> documentation;

    @JsonCreator
    public DeleteCustomerLinks(
            @JsonProperty("documentation") Optional<? extends DeleteCustomerDocumentation> documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
    }
    
    public DeleteCustomerLinks() {
        this(Optional.empty());
    }

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<DeleteCustomerDocumentation> documentation() {
        return (Optional<DeleteCustomerDocumentation>) documentation;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    public DeleteCustomerLinks withDocumentation(DeleteCustomerDocumentation documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = Optional.ofNullable(documentation);
        return this;
    }

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    public DeleteCustomerLinks withDocumentation(Optional<? extends DeleteCustomerDocumentation> documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteCustomerLinks other = (DeleteCustomerLinks) o;
        return 
            Objects.deepEquals(this.documentation, other.documentation);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            documentation);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteCustomerLinks.class,
                "documentation", documentation);
    }
    
    public final static class Builder {
 
        private Optional<? extends DeleteCustomerDocumentation> documentation = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The URL to the generic Mollie API error handling guide.
         */
        public Builder documentation(DeleteCustomerDocumentation documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = Optional.ofNullable(documentation);
            return this;
        }

        /**
         * The URL to the generic Mollie API error handling guide.
         */
        public Builder documentation(Optional<? extends DeleteCustomerDocumentation> documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = documentation;
            return this;
        }
        
        public DeleteCustomerLinks build() {
            return new DeleteCustomerLinks(
                documentation);
        }
    }
}
