/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mollie.mollie.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

public class ListChargebacksLinks {

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    @JsonProperty("documentation")
    private ListChargebacksDocumentation documentation;

    @JsonCreator
    public ListChargebacksLinks(
            @JsonProperty("documentation") ListChargebacksDocumentation documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
    }

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    @JsonIgnore
    public ListChargebacksDocumentation documentation() {
        return documentation;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The URL to the generic Mollie API error handling guide.
     */
    public ListChargebacksLinks withDocumentation(ListChargebacksDocumentation documentation) {
        Utils.checkNotNull(documentation, "documentation");
        this.documentation = documentation;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListChargebacksLinks other = (ListChargebacksLinks) o;
        return 
            Objects.deepEquals(this.documentation, other.documentation);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            documentation);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListChargebacksLinks.class,
                "documentation", documentation);
    }
    
    public final static class Builder {
 
        private ListChargebacksDocumentation documentation;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The URL to the generic Mollie API error handling guide.
         */
        public Builder documentation(ListChargebacksDocumentation documentation) {
            Utils.checkNotNull(documentation, "documentation");
            this.documentation = documentation;
            return this;
        }
        
        public ListChargebacksLinks build() {
            return new ListChargebacksLinks(
                documentation);
        }
    }
}
