/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie;

import static com.mollie.mollie.operations.Operations.RequestOperation;

import com.mollie.mollie.models.components.DeleteValuesSalesInvoice;
import com.mollie.mollie.models.components.SalesInvoiceRequest;
import com.mollie.mollie.models.operations.CreateSalesInvoiceRequest;
import com.mollie.mollie.models.operations.CreateSalesInvoiceRequestBuilder;
import com.mollie.mollie.models.operations.CreateSalesInvoiceResponse;
import com.mollie.mollie.models.operations.DeleteSalesInvoiceRequest;
import com.mollie.mollie.models.operations.DeleteSalesInvoiceRequestBuilder;
import com.mollie.mollie.models.operations.DeleteSalesInvoiceResponse;
import com.mollie.mollie.models.operations.GetSalesInvoiceRequest;
import com.mollie.mollie.models.operations.GetSalesInvoiceRequestBuilder;
import com.mollie.mollie.models.operations.GetSalesInvoiceResponse;
import com.mollie.mollie.models.operations.ListSalesInvoicesRequest;
import com.mollie.mollie.models.operations.ListSalesInvoicesRequestBuilder;
import com.mollie.mollie.models.operations.ListSalesInvoicesResponse;
import com.mollie.mollie.models.operations.UpdateSalesInvoiceRequest;
import com.mollie.mollie.models.operations.UpdateSalesInvoiceRequestBody;
import com.mollie.mollie.models.operations.UpdateSalesInvoiceRequestBuilder;
import com.mollie.mollie.models.operations.UpdateSalesInvoiceResponse;
import com.mollie.mollie.operations.CreateSalesInvoice;
import com.mollie.mollie.operations.DeleteSalesInvoice;
import com.mollie.mollie.operations.GetSalesInvoice;
import com.mollie.mollie.operations.ListSalesInvoices;
import com.mollie.mollie.operations.UpdateSalesInvoice;
import com.mollie.mollie.utils.Headers;
import com.mollie.mollie.utils.Options;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SalesInvoices {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSalesInvoices asyncSDK;

    SalesInvoices(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSalesInvoices(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSalesInvoices async() {
        return asyncSDK;
    }

    /**
     * Create sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>With the Sales Invoice API you can generate sales invoices to send to your customers.
     * 
     * @return The call builder
     */
    public CreateSalesInvoiceRequestBuilder create() {
        return new CreateSalesInvoiceRequestBuilder(sdkConfiguration);
    }

    /**
     * Create sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>With the Sales Invoice API you can generate sales invoices to send to your customers.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateSalesInvoiceResponse createDirect() {
        return create(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Create sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>With the Sales Invoice API you can generate sales invoices to send to your customers.
     * 
     * @param idempotencyKey A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     * @param salesInvoiceRequest 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateSalesInvoiceResponse create(
            Optional<String> idempotencyKey, Optional<? extends SalesInvoiceRequest> salesInvoiceRequest,
            Optional<Options> options) {
        CreateSalesInvoiceRequest request =
            CreateSalesInvoiceRequest
                .builder()
                .idempotencyKey(idempotencyKey)
                .salesInvoiceRequest(salesInvoiceRequest)
                .build();
        RequestOperation<CreateSalesInvoiceRequest, CreateSalesInvoiceResponse> operation
              = new CreateSalesInvoice.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List sales invoices
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Retrieve a list of all sales invoices created through the API.
     * 
     * <p>The results are paginated.
     * 
     * @return The call builder
     */
    public ListSalesInvoicesRequestBuilder list() {
        return new ListSalesInvoicesRequestBuilder(sdkConfiguration);
    }

    /**
     * List sales invoices
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Retrieve a list of all sales invoices created through the API.
     * 
     * <p>The results are paginated.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListSalesInvoicesResponse listDirect() {
        return list(JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * List sales invoices
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Retrieve a list of all sales invoices created through the API.
     * 
     * <p>The results are paginated.
     * 
     * @param from Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
     *         result set.
     * @param limit The maximum number of items to return. Defaults to 50 items.
     * @param testmode Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
     *         parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
     *         setting the `testmode` query parameter to `true`.
     *         
     *         Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
     * @param idempotencyKey A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListSalesInvoicesResponse list(
            JsonNullable<String> from, JsonNullable<Long> limit,
            Optional<Boolean> testmode, Optional<String> idempotencyKey,
            Optional<Options> options) {
        ListSalesInvoicesRequest request =
            ListSalesInvoicesRequest
                .builder()
                .from(from)
                .limit(limit)
                .testmode(testmode)
                .idempotencyKey(idempotencyKey)
                .build();
        RequestOperation<ListSalesInvoicesRequest, ListSalesInvoicesResponse> operation
              = new ListSalesInvoices.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Retrieve a single sales invoice by its ID.
     * 
     * @return The call builder
     */
    public GetSalesInvoiceRequestBuilder get() {
        return new GetSalesInvoiceRequestBuilder(sdkConfiguration);
    }

    /**
     * Get sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Retrieve a single sales invoice by its ID.
     * 
     * @param salesInvoiceId Provide the ID of the related sales invoice.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetSalesInvoiceResponse get(String salesInvoiceId) {
        return get(salesInvoiceId, Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * Get sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Retrieve a single sales invoice by its ID.
     * 
     * @param salesInvoiceId Provide the ID of the related sales invoice.
     * @param testmode Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
     *         parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
     *         setting the `testmode` query parameter to `true`.
     *         
     *         Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
     * @param idempotencyKey A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetSalesInvoiceResponse get(
            String salesInvoiceId, Optional<Boolean> testmode,
            Optional<String> idempotencyKey, Optional<Options> options) {
        GetSalesInvoiceRequest request =
            GetSalesInvoiceRequest
                .builder()
                .salesInvoiceId(salesInvoiceId)
                .testmode(testmode)
                .idempotencyKey(idempotencyKey)
                .build();
        RequestOperation<GetSalesInvoiceRequest, GetSalesInvoiceResponse> operation
              = new GetSalesInvoice.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Certain details of an existing sales invoice can be updated. For `draft` it is all values listed
     * below, but for
     * statuses `paid` and `issued` there are certain additional requirements (`paymentDetails` and
     * `emailDetails`,
     * respectively).
     * 
     * @return The call builder
     */
    public UpdateSalesInvoiceRequestBuilder update() {
        return new UpdateSalesInvoiceRequestBuilder(sdkConfiguration);
    }

    /**
     * Update sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Certain details of an existing sales invoice can be updated. For `draft` it is all values listed
     * below, but for
     * statuses `paid` and `issued` there are certain additional requirements (`paymentDetails` and
     * `emailDetails`,
     * respectively).
     * 
     * @param salesInvoiceId Provide the ID of the related sales invoice.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateSalesInvoiceResponse update(String salesInvoiceId) {
        return update(salesInvoiceId, Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * Update sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Certain details of an existing sales invoice can be updated. For `draft` it is all values listed
     * below, but for
     * statuses `paid` and `issued` there are certain additional requirements (`paymentDetails` and
     * `emailDetails`,
     * respectively).
     * 
     * @param salesInvoiceId Provide the ID of the related sales invoice.
     * @param idempotencyKey A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     * @param requestBody 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateSalesInvoiceResponse update(
            String salesInvoiceId, Optional<String> idempotencyKey,
            Optional<? extends UpdateSalesInvoiceRequestBody> requestBody, Optional<Options> options) {
        UpdateSalesInvoiceRequest request =
            UpdateSalesInvoiceRequest
                .builder()
                .salesInvoiceId(salesInvoiceId)
                .idempotencyKey(idempotencyKey)
                .requestBody(requestBody)
                .build();
        RequestOperation<UpdateSalesInvoiceRequest, UpdateSalesInvoiceResponse> operation
              = new UpdateSalesInvoice.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Sales invoices which are in status `draft` can be deleted. For all other statuses, please use the
     * [Update sales invoice](update-sales-invoice) endpoint instead.
     * 
     * @return The call builder
     */
    public DeleteSalesInvoiceRequestBuilder delete() {
        return new DeleteSalesInvoiceRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Sales invoices which are in status `draft` can be deleted. For all other statuses, please use the
     * [Update sales invoice](update-sales-invoice) endpoint instead.
     * 
     * @param salesInvoiceId Provide the ID of the related sales invoice.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteSalesInvoiceResponse delete(String salesInvoiceId) {
        return delete(salesInvoiceId, Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * Delete sales invoice
     * 
     * <p>&gt; 🚧 Beta feature
     * &gt;
     * &gt; This feature is currently in beta testing, and the final specification may still change.
     * 
     * <p>Sales invoices which are in status `draft` can be deleted. For all other statuses, please use the
     * [Update sales invoice](update-sales-invoice) endpoint instead.
     * 
     * @param salesInvoiceId Provide the ID of the related sales invoice.
     * @param idempotencyKey A unique key to ensure idempotent requests. This key should be a UUID v4 string.
     * @param deleteValuesSalesInvoice 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteSalesInvoiceResponse delete(
            String salesInvoiceId, Optional<String> idempotencyKey,
            Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice, Optional<Options> options) {
        DeleteSalesInvoiceRequest request =
            DeleteSalesInvoiceRequest
                .builder()
                .salesInvoiceId(salesInvoiceId)
                .idempotencyKey(idempotencyKey)
                .deleteValuesSalesInvoice(deleteValuesSalesInvoice)
                .build();
        RequestOperation<DeleteSalesInvoiceRequest, DeleteSalesInvoiceResponse> operation
              = new DeleteSalesInvoice.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
