/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.mollie.mollie.models.operations.async;

import static com.mollie.mollie.operations.Operations.AsyncRequestOperation;

import com.mollie.mollie.SDKConfiguration;
import com.mollie.mollie.models.components.DeleteValuesSalesInvoice;
import com.mollie.mollie.models.operations.DeleteSalesInvoiceRequest;
import com.mollie.mollie.operations.DeleteSalesInvoice;
import com.mollie.mollie.utils.Headers;
import com.mollie.mollie.utils.Options;
import com.mollie.mollie.utils.RetryConfig;
import com.mollie.mollie.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class DeleteSalesInvoiceRequestBuilder {

    private String id;
    private Optional<String> idempotencyKey = Optional.empty();
    private Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeleteSalesInvoiceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteSalesInvoiceRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
                
    public DeleteSalesInvoiceRequestBuilder idempotencyKey(String idempotencyKey) {
        Utils.checkNotNull(idempotencyKey, "idempotencyKey");
        this.idempotencyKey = Optional.of(idempotencyKey);
        return this;
    }

    public DeleteSalesInvoiceRequestBuilder idempotencyKey(Optional<String> idempotencyKey) {
        Utils.checkNotNull(idempotencyKey, "idempotencyKey");
        this.idempotencyKey = idempotencyKey;
        return this;
    }
                
    public DeleteSalesInvoiceRequestBuilder deleteValuesSalesInvoice(DeleteValuesSalesInvoice deleteValuesSalesInvoice) {
        Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
        this.deleteValuesSalesInvoice = Optional.of(deleteValuesSalesInvoice);
        return this;
    }

    public DeleteSalesInvoiceRequestBuilder deleteValuesSalesInvoice(Optional<? extends DeleteValuesSalesInvoice> deleteValuesSalesInvoice) {
        Utils.checkNotNull(deleteValuesSalesInvoice, "deleteValuesSalesInvoice");
        this.deleteValuesSalesInvoice = deleteValuesSalesInvoice;
        return this;
    }
                
    public DeleteSalesInvoiceRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public DeleteSalesInvoiceRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private DeleteSalesInvoiceRequest buildRequest() {

        DeleteSalesInvoiceRequest request = new DeleteSalesInvoiceRequest(id,
            idempotencyKey,
            deleteValuesSalesInvoice);

        return request;
    }

    public CompletableFuture<DeleteSalesInvoiceResponse> call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        AsyncRequestOperation<DeleteSalesInvoiceRequest, DeleteSalesInvoiceResponse> operation
              = new DeleteSalesInvoice.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        DeleteSalesInvoiceRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
