workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Mollie API:
        inputs:
            - location: https://raw.githubusercontent.com/mollie/openapi-specs/main/specs.yaml
        registry:
            location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-api
targets:
    client:
        target: java
        source: Mollie API
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-api-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
